-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fir_filter\Discrete_FIR_Filter_HDL_Optimized.vhd
-- Created: 2020-10-17 12:20:13
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Discrete_FIR_Filter_HDL_Optimized
-- Source Path: fir_filter/firFilter/Discrete FIR Filter HDL Optimized
-- Hierarchy Level: 1
-- 
-- Discrete FIR Filter HDL Optimized
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
--USE work.firFilter_pkg.ALL;
use work.top_level_pkg.all;

ENTITY Discrete_FIR_Filter_HDL_Optimized IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24
        validIn                           :   IN    std_logic;
        Coeff                             :   IN    vector_of_std_logic_vector24(0 TO 11);  -- sfix24_En23 [12]
        dataOut                           :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24
        validOut                          :   OUT   std_logic
        );
END Discrete_FIR_Filter_HDL_Optimized;


ARCHITECTURE rtl OF Discrete_FIR_Filter_HDL_Optimized IS

  -- Component Declarations
  COMPONENT FilterBank
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24
          validIn                         :   IN    std_logic;
          Coeff                           :   IN    vector_of_std_logic_vector24(0 TO 11);  -- sfix24_En23 [12]
          syncReset                       :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterBank
    USE ENTITY work.FilterBank(rtl);

  -- Signals
  SIGNAL syncReset                        : std_logic;
  SIGNAL dataOut_tmp                      : std_logic_vector(23 DOWNTO 0);  -- ufix24

BEGIN
  u_FilterBank : FilterBank
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => dataIn,  -- sfix24
              validIn => validIn,
              Coeff => Coeff,  -- sfix24_En23 [12]
              syncReset => syncReset,
              dataOut => dataOut_tmp,  -- sfix24
              validOut => validOut
              );

  syncReset <= '0';

  dataOut <= dataOut_tmp;

END rtl;

