-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fir_filter\FilterTapSystolicWvldin.vhd
-- Created: 2020-10-17 12:20:13
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FilterTapSystolicWvldin
-- Source Path: fir_filter/firFilter/Discrete FIR Filter HDL Optimized/FilterBank/subFilter/FilterTapSystolicWvldin
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FilterTapSystolicWvldin IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24
        coefIn_0                          :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En23
        addin                             :   IN    std_logic_vector(51 DOWNTO 0);  -- sfix52_En23
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dinDly2                           :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24
        tapout                            :   OUT   std_logic_vector(51 DOWNTO 0)  -- sfix52_En23
        );
END FilterTapSystolicWvldin;


ARCHITECTURE rtl OF FilterTapSystolicWvldin IS

  -- Signals
  SIGNAL dinReg2_0_re_signed              : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL coefIn_0_signed                  : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL addin_signed                     : signed(51 DOWNTO 0);  -- sfix52_En23
  SIGNAL fTap_din_reg1                    : signed(23 DOWNTO 0) := to_signed(16#000000#, 24);  -- sfix24
  SIGNAL fTap_coef_reg1                   : signed(23 DOWNTO 0) := to_signed(16#000000#, 24);  -- sfix24
  SIGNAL fTap_din_reg2                    : signed(23 DOWNTO 0) := to_signed(16#000000#, 24);  -- sfix24
  SIGNAL fTap_coef_reg2                   : signed(23 DOWNTO 0) := to_signed(16#000000#, 24);  -- sfix24
  SIGNAL fTap_mult_reg                    : signed(47 DOWNTO 0) := to_signed(0, 48);  -- sfix48
  SIGNAL fTap_addout_reg                  : signed(51 DOWNTO 0) := to_signed(0, 52);  -- sfix52
  SIGNAL fTap_din_reg1_next               : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL fTap_coef_reg1_next              : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL fTap_din_reg2_next               : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL fTap_coef_reg2_next              : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL fTap_mult_reg_next               : signed(47 DOWNTO 0);  -- sfix48_En23
  SIGNAL fTap_addout_reg_next             : signed(51 DOWNTO 0);  -- sfix52_En23
  SIGNAL dinDly2_tmp                      : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL tapout_tmp                       : signed(51 DOWNTO 0);  -- sfix52_En23

BEGIN
  dinReg2_0_re_signed <= signed(dinReg2_0_re);

  coefIn_0_signed <= signed(coefIn_0);

  addin_signed <= signed(addin);

  -- FilterTapSystlicWvldIn
  fTap_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        fTap_din_reg1 <= fTap_din_reg1_next;
        fTap_coef_reg1 <= fTap_coef_reg1_next;
        fTap_din_reg2 <= fTap_din_reg2_next;
        fTap_coef_reg2 <= fTap_coef_reg2_next;
        fTap_mult_reg <= fTap_mult_reg_next;
        fTap_addout_reg <= fTap_addout_reg_next;
      END IF;
    END IF;
  END PROCESS fTap_process;

  fTap_output : PROCESS (addin_signed, coefIn_0_signed, dinReg2_0_re_signed, dinRegVld, fTap_addout_reg,
       fTap_coef_reg1, fTap_coef_reg2, fTap_din_reg1, fTap_din_reg2,
       fTap_mult_reg)
    VARIABLE add_cast : signed(51 DOWNTO 0);
  BEGIN
    fTap_din_reg1_next <= fTap_din_reg1;
    fTap_coef_reg1_next <= fTap_coef_reg1;
    fTap_din_reg2_next <= fTap_din_reg2;
    fTap_coef_reg2_next <= fTap_coef_reg2;
    fTap_mult_reg_next <= fTap_mult_reg;
    fTap_addout_reg_next <= fTap_addout_reg;
    IF dinRegVld = '1' THEN 
      add_cast := resize(fTap_mult_reg, 52);
      fTap_addout_reg_next <= add_cast + addin_signed;
      fTap_mult_reg_next <= fTap_din_reg2 * fTap_coef_reg2;
      fTap_din_reg2_next <= fTap_din_reg1;
      fTap_coef_reg2_next <= fTap_coef_reg1;
      fTap_din_reg1_next <= dinReg2_0_re_signed;
      fTap_coef_reg1_next <= coefIn_0_signed;
    END IF;
    dinDly2_tmp <= fTap_din_reg2;
    tapout_tmp <= fTap_addout_reg;
  END PROCESS fTap_output;


  dinDly2 <= std_logic_vector(dinDly2_tmp);

  tapout <= std_logic_vector(tapout_tmp);

END rtl;

