-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fir_filter2\FIR_Filter_Subsystem_pkg.vhd
-- Created: 2020-10-23 15:41:08
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE FIR_Filter_Subsystem_pkg IS
  TYPE vector_of_std_logic_vector24 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(23 DOWNTO 0);
  TYPE vector_of_signed24 IS ARRAY (NATURAL RANGE <>) OF signed(23 DOWNTO 0);
END FIR_Filter_Subsystem_pkg;

