-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\LMSUpdateTester\LMSUpdate.vhd
-- Created: 2020-11-14 19:20:58
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LMSUpdate
-- Source Path: LMSUpdateTester/LMSUpdateSystem/LMSUpdate
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.top_level_pkg.ALL;

ENTITY LMSUpdate IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        X                                 :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        E                                 :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        Adapt                             :   IN    std_logic;
        W                                 :   OUT   vector_of_std_logic_vector24(0 TO 31)  -- sfix24_En24 [32]
        );
END LMSUpdate;


ARCHITECTURE rtl OF LMSUpdate IS

  -- Signals
  SIGNAL X_signed                         : signed(23 DOWNTO 0);  -- sfix24_En24
  SIGNAL E_signed                         : signed(23 DOWNTO 0);  -- sfix24_En24
  SIGNAL W_tmp                            : vector_of_signed24(0 TO 31);  -- sfix24_En24 [32]
  SIGNAL xBuffer                          : vector_of_signed24(0 TO 31);  -- sfix24 [32]
  SIGNAL wBuffer                          : vector_of_signed24(0 TO 31);  -- sfix24 [32]
  SIGNAL xBuffer_next                     : vector_of_signed24(0 TO 31);  -- sfix24_En24 [32]
  SIGNAL wBuffer_next                     : vector_of_signed24(0 TO 31);  -- sfix24_En24 [32]

BEGIN
  X_signed <= signed(X);

  E_signed <= signed(E);

    LMSUpdate_1_process : PROCESS (clk)
    BEGIN
        IF clk'EVENT AND clk = '1' THEN
            IF reset = '1' THEN
                xBuffer <= (OTHERS => to_signed(16#000000#, 24));
                wBuffer <= (OTHERS => to_signed(16#000000#, 24));
            ELSIF enb = '1' THEN
                xBuffer <= xBuffer_next;
                wBuffer <= wBuffer_next;
            END IF;
        END IF;
    END PROCESS LMSUpdate_1_process;

  LMSUpdate_1_output : PROCESS (Adapt, E_signed, X_signed, wBuffer, xBuffer)
    VARIABLE xBuffer_temp   : vector_of_signed24(0 TO 31) := (OTHERS => (OTHERS => '0'));
    VARIABLE wBuffer_temp   : vector_of_signed24(0 TO 31) := (OTHERS => (OTHERS => '0'));
    VARIABLE add_cast       : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast           : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp       : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_0     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp       : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_1     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_0         : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_0     : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_2     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_0     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_3     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_1         : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_1     : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_4     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_1     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_5     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_2         : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_2     : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_6     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_2     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_7     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_3         : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_3     : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_8     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_3     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_9     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_4         : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_4     : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_10    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_4     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_11    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_5         : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_5     : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_12    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_5     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_13    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_6         : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_6     : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_14    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_6     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_15    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_7         : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_7     : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_16    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_7     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_17    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_8         : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_8     : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_18    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_8     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_19    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_9         : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_9     : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_20    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_9     : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_21    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_10        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_10    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_22    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_10    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_23    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_11        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_11    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_24    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_11    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_25    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_12        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_12    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_26    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_12    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_27    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_13        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_13    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_28    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_13    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_29    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_14        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_14    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_30    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_14    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_31    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_15        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_15    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_32    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_15    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_33    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_16        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_16    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_34    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_16    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_35    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_17        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_17    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_36    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_17    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_37    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_18        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_18    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_38    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_18    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_39    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_19        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_19    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_40    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_19    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_41    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_20        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_20    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_42    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_20    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_43    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_21        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_21    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_44    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_21    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_45    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_22        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_22    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_46    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_22    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_47    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_23        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_23    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_48    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_23    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_49    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_24        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_24    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_50    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_24    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_51    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_25        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_25    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_52    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_25    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_53    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_26        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_26    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_54    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_26    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_55    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_27        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_27    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_56    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_27    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_57    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_28        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_28    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_58    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_28    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_59    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_29        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_29    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_60    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_29    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_61    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE cast_30        : signed(47 DOWNTO 0) := (OTHERS => '0');
    VARIABLE mul_temp_30    : signed(71 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_cast_62    : signed(74 DOWNTO 0) := (OTHERS => '0');
    VARIABLE add_temp_30    : signed(74 DOWNTO 0) := (OTHERS => '0');
  BEGIN
    xBuffer_temp := xBuffer;
    wBuffer_temp := wBuffer;
    -- W = weights
    -- X = input
    -- E = error
    -- mu = step size
    -- L = length
    -- X delay pipeline
    -- W delay pipeline
    xBuffer_temp(1 TO 31) := xBuffer(0 TO 30);
    xBuffer_temp(0) := X_signed;
    IF Adapt = '1' THEN 
      add_cast := resize(wBuffer(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp := cast * X_signed;
      add_cast_0 := resize(mul_temp, 75);
      add_temp := add_cast + add_cast_0;
      IF ((add_temp(74) = '0') AND (add_temp(73) /= '0')) OR ((add_temp(74) = '0') AND (add_temp(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(0) := X"7FFFFF";
      ELSIF (add_temp(74) = '1') AND (add_temp(73) /= '1') THEN 
        wBuffer_temp(0) := X"800000";
      ELSE 
        wBuffer_temp(0) := add_temp(73 DOWNTO 50) + ('0' & add_temp(49));
      END IF;
      add_cast_1 := resize(wBuffer(1) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_0 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_0 := cast_0 * xBuffer_temp(1);
      add_cast_2 := resize(mul_temp_0, 75);
      add_temp_0 := add_cast_1 + add_cast_2;
      IF ((add_temp_0(74) = '0') AND (add_temp_0(73) /= '0')) OR ((add_temp_0(74) = '0') AND (add_temp_0(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(1) := X"7FFFFF";
      ELSIF (add_temp_0(74) = '1') AND (add_temp_0(73) /= '1') THEN 
        wBuffer_temp(1) := X"800000";
      ELSE 
        wBuffer_temp(1) := add_temp_0(73 DOWNTO 50) + ('0' & add_temp_0(49));
      END IF;
      add_cast_3 := resize(wBuffer(2) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_1 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_1 := cast_1 * xBuffer_temp(2);
      add_cast_4 := resize(mul_temp_1, 75);
      add_temp_1 := add_cast_3 + add_cast_4;
      IF ((add_temp_1(74) = '0') AND (add_temp_1(73) /= '0')) OR ((add_temp_1(74) = '0') AND (add_temp_1(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(2) := X"7FFFFF";
      ELSIF (add_temp_1(74) = '1') AND (add_temp_1(73) /= '1') THEN 
        wBuffer_temp(2) := X"800000";
      ELSE 
        wBuffer_temp(2) := add_temp_1(73 DOWNTO 50) + ('0' & add_temp_1(49));
      END IF;
      add_cast_5 := resize(wBuffer(3) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_2 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_2 := cast_2 * xBuffer_temp(3);
      add_cast_6 := resize(mul_temp_2, 75);
      add_temp_2 := add_cast_5 + add_cast_6;
      IF ((add_temp_2(74) = '0') AND (add_temp_2(73) /= '0')) OR ((add_temp_2(74) = '0') AND (add_temp_2(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(3) := X"7FFFFF";
      ELSIF (add_temp_2(74) = '1') AND (add_temp_2(73) /= '1') THEN 
        wBuffer_temp(3) := X"800000";
      ELSE 
        wBuffer_temp(3) := add_temp_2(73 DOWNTO 50) + ('0' & add_temp_2(49));
      END IF;
      add_cast_7 := resize(wBuffer(4) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_3 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_3 := cast_3 * xBuffer_temp(4);
      add_cast_8 := resize(mul_temp_3, 75);
      add_temp_3 := add_cast_7 + add_cast_8;
      IF ((add_temp_3(74) = '0') AND (add_temp_3(73) /= '0')) OR ((add_temp_3(74) = '0') AND (add_temp_3(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(4) := X"7FFFFF";
      ELSIF (add_temp_3(74) = '1') AND (add_temp_3(73) /= '1') THEN 
        wBuffer_temp(4) := X"800000";
      ELSE 
        wBuffer_temp(4) := add_temp_3(73 DOWNTO 50) + ('0' & add_temp_3(49));
      END IF;
      add_cast_9 := resize(wBuffer(5) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_4 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_4 := cast_4 * xBuffer_temp(5);
      add_cast_10 := resize(mul_temp_4, 75);
      add_temp_4 := add_cast_9 + add_cast_10;
      IF ((add_temp_4(74) = '0') AND (add_temp_4(73) /= '0')) OR ((add_temp_4(74) = '0') AND (add_temp_4(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(5) := X"7FFFFF";
      ELSIF (add_temp_4(74) = '1') AND (add_temp_4(73) /= '1') THEN 
        wBuffer_temp(5) := X"800000";
      ELSE 
        wBuffer_temp(5) := add_temp_4(73 DOWNTO 50) + ('0' & add_temp_4(49));
      END IF;
      add_cast_11 := resize(wBuffer(6) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_5 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_5 := cast_5 * xBuffer_temp(6);
      add_cast_12 := resize(mul_temp_5, 75);
      add_temp_5 := add_cast_11 + add_cast_12;
      IF ((add_temp_5(74) = '0') AND (add_temp_5(73) /= '0')) OR ((add_temp_5(74) = '0') AND (add_temp_5(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(6) := X"7FFFFF";
      ELSIF (add_temp_5(74) = '1') AND (add_temp_5(73) /= '1') THEN 
        wBuffer_temp(6) := X"800000";
      ELSE 
        wBuffer_temp(6) := add_temp_5(73 DOWNTO 50) + ('0' & add_temp_5(49));
      END IF;
      add_cast_13 := resize(wBuffer(7) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_6 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_6 := cast_6 * xBuffer_temp(7);
      add_cast_14 := resize(mul_temp_6, 75);
      add_temp_6 := add_cast_13 + add_cast_14;
      IF ((add_temp_6(74) = '0') AND (add_temp_6(73) /= '0')) OR ((add_temp_6(74) = '0') AND (add_temp_6(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(7) := X"7FFFFF";
      ELSIF (add_temp_6(74) = '1') AND (add_temp_6(73) /= '1') THEN 
        wBuffer_temp(7) := X"800000";
      ELSE 
        wBuffer_temp(7) := add_temp_6(73 DOWNTO 50) + ('0' & add_temp_6(49));
      END IF;
      add_cast_15 := resize(wBuffer(8) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_7 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_7 := cast_7 * xBuffer_temp(8);
      add_cast_16 := resize(mul_temp_7, 75);
      add_temp_7 := add_cast_15 + add_cast_16;
      IF ((add_temp_7(74) = '0') AND (add_temp_7(73) /= '0')) OR ((add_temp_7(74) = '0') AND (add_temp_7(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(8) := X"7FFFFF";
      ELSIF (add_temp_7(74) = '1') AND (add_temp_7(73) /= '1') THEN 
        wBuffer_temp(8) := X"800000";
      ELSE 
        wBuffer_temp(8) := add_temp_7(73 DOWNTO 50) + ('0' & add_temp_7(49));
      END IF;
      add_cast_17 := resize(wBuffer(9) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_8 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_8 := cast_8 * xBuffer_temp(9);
      add_cast_18 := resize(mul_temp_8, 75);
      add_temp_8 := add_cast_17 + add_cast_18;
      IF ((add_temp_8(74) = '0') AND (add_temp_8(73) /= '0')) OR ((add_temp_8(74) = '0') AND (add_temp_8(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(9) := X"7FFFFF";
      ELSIF (add_temp_8(74) = '1') AND (add_temp_8(73) /= '1') THEN 
        wBuffer_temp(9) := X"800000";
      ELSE 
        wBuffer_temp(9) := add_temp_8(73 DOWNTO 50) + ('0' & add_temp_8(49));
      END IF;
      add_cast_19 := resize(wBuffer(10) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_9 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_9 := cast_9 * xBuffer_temp(10);
      add_cast_20 := resize(mul_temp_9, 75);
      add_temp_9 := add_cast_19 + add_cast_20;
      IF ((add_temp_9(74) = '0') AND (add_temp_9(73) /= '0')) OR ((add_temp_9(74) = '0') AND (add_temp_9(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(10) := X"7FFFFF";
      ELSIF (add_temp_9(74) = '1') AND (add_temp_9(73) /= '1') THEN 
        wBuffer_temp(10) := X"800000";
      ELSE 
        wBuffer_temp(10) := add_temp_9(73 DOWNTO 50) + ('0' & add_temp_9(49));
      END IF;
      add_cast_21 := resize(wBuffer(11) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_10 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_10 := cast_10 * xBuffer_temp(11);
      add_cast_22 := resize(mul_temp_10, 75);
      add_temp_10 := add_cast_21 + add_cast_22;
      IF ((add_temp_10(74) = '0') AND (add_temp_10(73) /= '0')) OR ((add_temp_10(74) = '0') AND (add_temp_10(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(11) := X"7FFFFF";
      ELSIF (add_temp_10(74) = '1') AND (add_temp_10(73) /= '1') THEN 
        wBuffer_temp(11) := X"800000";
      ELSE 
        wBuffer_temp(11) := add_temp_10(73 DOWNTO 50) + ('0' & add_temp_10(49));
      END IF;
      add_cast_23 := resize(wBuffer(12) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_11 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_11 := cast_11 * xBuffer_temp(12);
      add_cast_24 := resize(mul_temp_11, 75);
      add_temp_11 := add_cast_23 + add_cast_24;
      IF ((add_temp_11(74) = '0') AND (add_temp_11(73) /= '0')) OR ((add_temp_11(74) = '0') AND (add_temp_11(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(12) := X"7FFFFF";
      ELSIF (add_temp_11(74) = '1') AND (add_temp_11(73) /= '1') THEN 
        wBuffer_temp(12) := X"800000";
      ELSE 
        wBuffer_temp(12) := add_temp_11(73 DOWNTO 50) + ('0' & add_temp_11(49));
      END IF;
      add_cast_25 := resize(wBuffer(13) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_12 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_12 := cast_12 * xBuffer_temp(13);
      add_cast_26 := resize(mul_temp_12, 75);
      add_temp_12 := add_cast_25 + add_cast_26;
      IF ((add_temp_12(74) = '0') AND (add_temp_12(73) /= '0')) OR ((add_temp_12(74) = '0') AND (add_temp_12(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(13) := X"7FFFFF";
      ELSIF (add_temp_12(74) = '1') AND (add_temp_12(73) /= '1') THEN 
        wBuffer_temp(13) := X"800000";
      ELSE 
        wBuffer_temp(13) := add_temp_12(73 DOWNTO 50) + ('0' & add_temp_12(49));
      END IF;
      add_cast_27 := resize(wBuffer(14) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_13 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_13 := cast_13 * xBuffer_temp(14);
      add_cast_28 := resize(mul_temp_13, 75);
      add_temp_13 := add_cast_27 + add_cast_28;
      IF ((add_temp_13(74) = '0') AND (add_temp_13(73) /= '0')) OR ((add_temp_13(74) = '0') AND (add_temp_13(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(14) := X"7FFFFF";
      ELSIF (add_temp_13(74) = '1') AND (add_temp_13(73) /= '1') THEN 
        wBuffer_temp(14) := X"800000";
      ELSE 
        wBuffer_temp(14) := add_temp_13(73 DOWNTO 50) + ('0' & add_temp_13(49));
      END IF;
      add_cast_29 := resize(wBuffer(15) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_14 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_14 := cast_14 * xBuffer_temp(15);
      add_cast_30 := resize(mul_temp_14, 75);
      add_temp_14 := add_cast_29 + add_cast_30;
      IF ((add_temp_14(74) = '0') AND (add_temp_14(73) /= '0')) OR ((add_temp_14(74) = '0') AND (add_temp_14(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(15) := X"7FFFFF";
      ELSIF (add_temp_14(74) = '1') AND (add_temp_14(73) /= '1') THEN 
        wBuffer_temp(15) := X"800000";
      ELSE 
        wBuffer_temp(15) := add_temp_14(73 DOWNTO 50) + ('0' & add_temp_14(49));
      END IF;
      add_cast_31 := resize(wBuffer(16) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_15 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_15 := cast_15 * xBuffer_temp(16);
      add_cast_32 := resize(mul_temp_15, 75);
      add_temp_15 := add_cast_31 + add_cast_32;
      IF ((add_temp_15(74) = '0') AND (add_temp_15(73) /= '0')) OR ((add_temp_15(74) = '0') AND (add_temp_15(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(16) := X"7FFFFF";
      ELSIF (add_temp_15(74) = '1') AND (add_temp_15(73) /= '1') THEN 
        wBuffer_temp(16) := X"800000";
      ELSE 
        wBuffer_temp(16) := add_temp_15(73 DOWNTO 50) + ('0' & add_temp_15(49));
      END IF;
      add_cast_33 := resize(wBuffer(17) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_16 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_16 := cast_16 * xBuffer_temp(17);
      add_cast_34 := resize(mul_temp_16, 75);
      add_temp_16 := add_cast_33 + add_cast_34;
      IF ((add_temp_16(74) = '0') AND (add_temp_16(73) /= '0')) OR ((add_temp_16(74) = '0') AND (add_temp_16(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(17) := X"7FFFFF";
      ELSIF (add_temp_16(74) = '1') AND (add_temp_16(73) /= '1') THEN 
        wBuffer_temp(17) := X"800000";
      ELSE 
        wBuffer_temp(17) := add_temp_16(73 DOWNTO 50) + ('0' & add_temp_16(49));
      END IF;
      add_cast_35 := resize(wBuffer(18) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_17 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_17 := cast_17 * xBuffer_temp(18);
      add_cast_36 := resize(mul_temp_17, 75);
      add_temp_17 := add_cast_35 + add_cast_36;
      IF ((add_temp_17(74) = '0') AND (add_temp_17(73) /= '0')) OR ((add_temp_17(74) = '0') AND (add_temp_17(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(18) := X"7FFFFF";
      ELSIF (add_temp_17(74) = '1') AND (add_temp_17(73) /= '1') THEN 
        wBuffer_temp(18) := X"800000";
      ELSE 
        wBuffer_temp(18) := add_temp_17(73 DOWNTO 50) + ('0' & add_temp_17(49));
      END IF;
      add_cast_37 := resize(wBuffer(19) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_18 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_18 := cast_18 * xBuffer_temp(19);
      add_cast_38 := resize(mul_temp_18, 75);
      add_temp_18 := add_cast_37 + add_cast_38;
      IF ((add_temp_18(74) = '0') AND (add_temp_18(73) /= '0')) OR ((add_temp_18(74) = '0') AND (add_temp_18(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(19) := X"7FFFFF";
      ELSIF (add_temp_18(74) = '1') AND (add_temp_18(73) /= '1') THEN 
        wBuffer_temp(19) := X"800000";
      ELSE 
        wBuffer_temp(19) := add_temp_18(73 DOWNTO 50) + ('0' & add_temp_18(49));
      END IF;
      add_cast_39 := resize(wBuffer(20) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_19 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_19 := cast_19 * xBuffer_temp(20);
      add_cast_40 := resize(mul_temp_19, 75);
      add_temp_19 := add_cast_39 + add_cast_40;
      IF ((add_temp_19(74) = '0') AND (add_temp_19(73) /= '0')) OR ((add_temp_19(74) = '0') AND (add_temp_19(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(20) := X"7FFFFF";
      ELSIF (add_temp_19(74) = '1') AND (add_temp_19(73) /= '1') THEN 
        wBuffer_temp(20) := X"800000";
      ELSE 
        wBuffer_temp(20) := add_temp_19(73 DOWNTO 50) + ('0' & add_temp_19(49));
      END IF;
      add_cast_41 := resize(wBuffer(21) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_20 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_20 := cast_20 * xBuffer_temp(21);
      add_cast_42 := resize(mul_temp_20, 75);
      add_temp_20 := add_cast_41 + add_cast_42;
      IF ((add_temp_20(74) = '0') AND (add_temp_20(73) /= '0')) OR ((add_temp_20(74) = '0') AND (add_temp_20(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(21) := X"7FFFFF";
      ELSIF (add_temp_20(74) = '1') AND (add_temp_20(73) /= '1') THEN 
        wBuffer_temp(21) := X"800000";
      ELSE 
        wBuffer_temp(21) := add_temp_20(73 DOWNTO 50) + ('0' & add_temp_20(49));
      END IF;
      add_cast_43 := resize(wBuffer(22) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_21 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_21 := cast_21 * xBuffer_temp(22);
      add_cast_44 := resize(mul_temp_21, 75);
      add_temp_21 := add_cast_43 + add_cast_44;
      IF ((add_temp_21(74) = '0') AND (add_temp_21(73) /= '0')) OR ((add_temp_21(74) = '0') AND (add_temp_21(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(22) := X"7FFFFF";
      ELSIF (add_temp_21(74) = '1') AND (add_temp_21(73) /= '1') THEN 
        wBuffer_temp(22) := X"800000";
      ELSE 
        wBuffer_temp(22) := add_temp_21(73 DOWNTO 50) + ('0' & add_temp_21(49));
      END IF;
      add_cast_45 := resize(wBuffer(23) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_22 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_22 := cast_22 * xBuffer_temp(23);
      add_cast_46 := resize(mul_temp_22, 75);
      add_temp_22 := add_cast_45 + add_cast_46;
      IF ((add_temp_22(74) = '0') AND (add_temp_22(73) /= '0')) OR ((add_temp_22(74) = '0') AND (add_temp_22(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(23) := X"7FFFFF";
      ELSIF (add_temp_22(74) = '1') AND (add_temp_22(73) /= '1') THEN 
        wBuffer_temp(23) := X"800000";
      ELSE 
        wBuffer_temp(23) := add_temp_22(73 DOWNTO 50) + ('0' & add_temp_22(49));
      END IF;
      add_cast_47 := resize(wBuffer(24) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_23 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_23 := cast_23 * xBuffer_temp(24);
      add_cast_48 := resize(mul_temp_23, 75);
      add_temp_23 := add_cast_47 + add_cast_48;
      IF ((add_temp_23(74) = '0') AND (add_temp_23(73) /= '0')) OR ((add_temp_23(74) = '0') AND (add_temp_23(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(24) := X"7FFFFF";
      ELSIF (add_temp_23(74) = '1') AND (add_temp_23(73) /= '1') THEN 
        wBuffer_temp(24) := X"800000";
      ELSE 
        wBuffer_temp(24) := add_temp_23(73 DOWNTO 50) + ('0' & add_temp_23(49));
      END IF;
      add_cast_49 := resize(wBuffer(25) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_24 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_24 := cast_24 * xBuffer_temp(25);
      add_cast_50 := resize(mul_temp_24, 75);
      add_temp_24 := add_cast_49 + add_cast_50;
      IF ((add_temp_24(74) = '0') AND (add_temp_24(73) /= '0')) OR ((add_temp_24(74) = '0') AND (add_temp_24(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(25) := X"7FFFFF";
      ELSIF (add_temp_24(74) = '1') AND (add_temp_24(73) /= '1') THEN 
        wBuffer_temp(25) := X"800000";
      ELSE 
        wBuffer_temp(25) := add_temp_24(73 DOWNTO 50) + ('0' & add_temp_24(49));
      END IF;
      add_cast_51 := resize(wBuffer(26) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_25 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_25 := cast_25 * xBuffer_temp(26);
      add_cast_52 := resize(mul_temp_25, 75);
      add_temp_25 := add_cast_51 + add_cast_52;
      IF ((add_temp_25(74) = '0') AND (add_temp_25(73) /= '0')) OR ((add_temp_25(74) = '0') AND (add_temp_25(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(26) := X"7FFFFF";
      ELSIF (add_temp_25(74) = '1') AND (add_temp_25(73) /= '1') THEN 
        wBuffer_temp(26) := X"800000";
      ELSE 
        wBuffer_temp(26) := add_temp_25(73 DOWNTO 50) + ('0' & add_temp_25(49));
      END IF;
      add_cast_53 := resize(wBuffer(27) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_26 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_26 := cast_26 * xBuffer_temp(27);
      add_cast_54 := resize(mul_temp_26, 75);
      add_temp_26 := add_cast_53 + add_cast_54;
      IF ((add_temp_26(74) = '0') AND (add_temp_26(73) /= '0')) OR ((add_temp_26(74) = '0') AND (add_temp_26(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(27) := X"7FFFFF";
      ELSIF (add_temp_26(74) = '1') AND (add_temp_26(73) /= '1') THEN 
        wBuffer_temp(27) := X"800000";
      ELSE 
        wBuffer_temp(27) := add_temp_26(73 DOWNTO 50) + ('0' & add_temp_26(49));
      END IF;
      add_cast_55 := resize(wBuffer(28) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_27 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_27 := cast_27 * xBuffer_temp(28);
      add_cast_56 := resize(mul_temp_27, 75);
      add_temp_27 := add_cast_55 + add_cast_56;
      IF ((add_temp_27(74) = '0') AND (add_temp_27(73) /= '0')) OR ((add_temp_27(74) = '0') AND (add_temp_27(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(28) := X"7FFFFF";
      ELSIF (add_temp_27(74) = '1') AND (add_temp_27(73) /= '1') THEN 
        wBuffer_temp(28) := X"800000";
      ELSE 
        wBuffer_temp(28) := add_temp_27(73 DOWNTO 50) + ('0' & add_temp_27(49));
      END IF;
      add_cast_57 := resize(wBuffer(29) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_28 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_28 := cast_28 * xBuffer_temp(29);
      add_cast_58 := resize(mul_temp_28, 75);
      add_temp_28 := add_cast_57 + add_cast_58;
      IF ((add_temp_28(74) = '0') AND (add_temp_28(73) /= '0')) OR ((add_temp_28(74) = '0') AND (add_temp_28(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(29) := X"7FFFFF";
      ELSIF (add_temp_28(74) = '1') AND (add_temp_28(73) /= '1') THEN 
        wBuffer_temp(29) := X"800000";
      ELSE 
        wBuffer_temp(29) := add_temp_28(73 DOWNTO 50) + ('0' & add_temp_28(49));
      END IF;
      add_cast_59 := resize(wBuffer(30) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_29 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_29 := cast_29 * xBuffer_temp(30);
      add_cast_60 := resize(mul_temp_29, 75);
      add_temp_29 := add_cast_59 + add_cast_60;
      IF ((add_temp_29(74) = '0') AND (add_temp_29(73) /= '0')) OR ((add_temp_29(74) = '0') AND (add_temp_29(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(30) := X"7FFFFF";
      ELSIF (add_temp_29(74) = '1') AND (add_temp_29(73) /= '1') THEN 
        wBuffer_temp(30) := X"800000";
      ELSE 
        wBuffer_temp(30) := add_temp_29(73 DOWNTO 50) + ('0' & add_temp_29(49));
      END IF;
      add_cast_61 := resize(wBuffer(31) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 75);
      cast_30 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_30 := cast_30 * xBuffer_temp(31);
      add_cast_62 := resize(mul_temp_30, 75);
      add_temp_30 := add_cast_61 + add_cast_62;
      IF ((add_temp_30(74) = '0') AND (add_temp_30(73) /= '0')) OR ((add_temp_30(74) = '0') AND (add_temp_30(73 DOWNTO 50) = X"7FFFFF")) THEN 
        wBuffer_temp(31) := X"7FFFFF";
      ELSIF (add_temp_30(74) = '1') AND (add_temp_30(73) /= '1') THEN 
        wBuffer_temp(31) := X"800000";
      ELSE 
        wBuffer_temp(31) := add_temp_30(73 DOWNTO 50) + ('0' & add_temp_30(49));
      END IF;
      --wBuffer(:) = (wBuffer) + 0.0625*E*(xBuffer);
      --the above statement has been unwrapped to force HDL coder to not
      --use FOR-GENERATE statements
    END IF;
    W_tmp <= wBuffer_temp;
    xBuffer_next <= xBuffer_temp;
    wBuffer_next <= wBuffer_temp;
  END PROCESS LMSUpdate_1_output;


  outputgen: FOR k IN 0 TO 31 GENERATE
    W(k) <= std_logic_vector(W_tmp(k));
  END GENERATE;

END rtl;

