-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\LMSUpdateTester\LMSUpdate.vhd
-- Created: 2020-10-27 15:48:19
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: LMSUpdate
-- Source Path: LMSUpdateTester/LMSUpdateSystem/LMSUpdate
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.top_level_pkg.ALL;

ENTITY LMSUpdate IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        X                                 :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        E                                 :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        Adapt                             :   IN    std_logic;
        W                                 :   OUT   vector_of_std_logic_vector24(0 TO 11)  -- sfix24_En24 [12]
        );
END LMSUpdate;


ARCHITECTURE rtl OF LMSUpdate IS

  -- Signals
  SIGNAL X_signed                         : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL E_signed                         : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL W_tmp                            : vector_of_signed24(0 TO 11) := (others => (others => '0'));  -- sfix24_En24 [12]
  SIGNAL xBuffer                          : vector_of_signed24(0 TO 11) := (others => (others => '0'));  -- sfix24 [12]
  SIGNAL wBuffer                          : vector_of_signed24(0 TO 11) := (others => (others => '0'));  -- sfix24 [12]
  SIGNAL xBuffer_next                     : vector_of_signed24(0 TO 11) := (others => (others => '0'));  -- sfix24_En24 [12]
  SIGNAL wBuffer_next                     : vector_of_signed24(0 TO 11) := (others => (others => '0'));  -- sfix24_En24 [12]

BEGIN
  X_signed <= signed(X);

  E_signed <= signed(E);

  LMSUpdate_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        xBuffer <= (OTHERS => to_signed(16#000000#, 24));
        wBuffer <= (OTHERS => to_signed(16#000000#, 24));
      ELSIF enb = '1' THEN
        xBuffer <= xBuffer_next;
        wBuffer <= wBuffer_next;
      END IF;
   END IF;
  END PROCESS LMSUpdate_1_process;
 
  LMSUpdate_1_output : PROCESS (Adapt, E_signed, X_signed, wBuffer, xBuffer)
    VARIABLE xBuffer_temp   : vector_of_signed24(0 TO 11) := (others => (others => '0'));
    VARIABLE wBuffer_temp   : vector_of_signed24(0 TO 11) := (others => (others => '0'));
    VARIABLE add_cast       : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast           : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp       : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_0     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp       : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_1     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast_0         : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp_0     : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_2     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp_0     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_3     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast_1         : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp_1     : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_4     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp_1     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_5     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast_2         : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp_2     : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_6     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp_2     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_7     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast_3         : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp_3     : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_8     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp_3     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_9     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast_4         : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp_4     : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_10    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp_4     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_11    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast_5         : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp_5     : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_12    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp_5     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_13    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast_6         : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp_6     : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_14    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp_6     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_15    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast_7         : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp_7     : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_16    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp_7     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_17    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast_8         : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp_8     : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_18    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp_8     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_19    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast_9         : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp_9     : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_20    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp_9     : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_21    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE cast_10        : signed(47 DOWNTO 0) := (others => '0');
    VARIABLE mul_temp_10    : signed(71 DOWNTO 0) := (others => '0');
    VARIABLE add_cast_22    : signed(72 DOWNTO 0) := (others => '0');
    VARIABLE add_temp_10    : signed(72 DOWNTO 0) := (others => '0');
  BEGIN
    xBuffer_temp := xBuffer;
    wBuffer_temp := wBuffer;
    -- W = weights
    -- X = input
    -- E = error
    -- mu = step size
    -- L = length
    -- X delay pipeline
    -- W delay pipeline
    xBuffer_temp(1 TO 11) := xBuffer(0 TO 10);
    xBuffer_temp(0) := X_signed;
    IF Adapt = '1' THEN 
      add_cast := resize(wBuffer(0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp := cast * X_signed;
      add_cast_0 := resize(mul_temp, 73);
      add_temp := add_cast + add_cast_0;
      IF ((add_temp(72) = '0') AND (add_temp(71 DOWNTO 70) /= "00")) OR ((add_temp(72) = '0') AND (add_temp(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(0) := X"7FFFFF";
      ELSIF (add_temp(72) = '1') AND (add_temp(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(0) := X"800000";
      ELSE 
        wBuffer_temp(0) := add_temp(70 DOWNTO 47) + ('0' & add_temp(46));
      END IF;
      add_cast_1 := resize(wBuffer(1) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast_0 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_0 := cast_0 * xBuffer_temp(1);
      add_cast_2 := resize(mul_temp_0, 73);
      add_temp_0 := add_cast_1 + add_cast_2;
      IF ((add_temp_0(72) = '0') AND (add_temp_0(71 DOWNTO 70) /= "00")) OR ((add_temp_0(72) = '0') AND (add_temp_0(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(1) := X"7FFFFF";
      ELSIF (add_temp_0(72) = '1') AND (add_temp_0(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(1) := X"800000";
      ELSE 
        wBuffer_temp(1) := add_temp_0(70 DOWNTO 47) + ('0' & add_temp_0(46));
      END IF;
      add_cast_3 := resize(wBuffer(2) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast_1 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_1 := cast_1 * xBuffer_temp(2);
      add_cast_4 := resize(mul_temp_1, 73);
      add_temp_1 := add_cast_3 + add_cast_4;
      IF ((add_temp_1(72) = '0') AND (add_temp_1(71 DOWNTO 70) /= "00")) OR ((add_temp_1(72) = '0') AND (add_temp_1(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(2) := X"7FFFFF";
      ELSIF (add_temp_1(72) = '1') AND (add_temp_1(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(2) := X"800000";
      ELSE 
        wBuffer_temp(2) := add_temp_1(70 DOWNTO 47) + ('0' & add_temp_1(46));
      END IF;
      add_cast_5 := resize(wBuffer(3) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast_2 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_2 := cast_2 * xBuffer_temp(3);
      add_cast_6 := resize(mul_temp_2, 73);
      add_temp_2 := add_cast_5 + add_cast_6;
      IF ((add_temp_2(72) = '0') AND (add_temp_2(71 DOWNTO 70) /= "00")) OR ((add_temp_2(72) = '0') AND (add_temp_2(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(3) := X"7FFFFF";
      ELSIF (add_temp_2(72) = '1') AND (add_temp_2(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(3) := X"800000";
      ELSE 
        wBuffer_temp(3) := add_temp_2(70 DOWNTO 47) + ('0' & add_temp_2(46));
      END IF;
      add_cast_7 := resize(wBuffer(4) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast_3 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_3 := cast_3 * xBuffer_temp(4);
      add_cast_8 := resize(mul_temp_3, 73);
      add_temp_3 := add_cast_7 + add_cast_8;
      IF ((add_temp_3(72) = '0') AND (add_temp_3(71 DOWNTO 70) /= "00")) OR ((add_temp_3(72) = '0') AND (add_temp_3(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(4) := X"7FFFFF";
      ELSIF (add_temp_3(72) = '1') AND (add_temp_3(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(4) := X"800000";
      ELSE 
        wBuffer_temp(4) := add_temp_3(70 DOWNTO 47) + ('0' & add_temp_3(46));
      END IF;
      add_cast_9 := resize(wBuffer(5) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast_4 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_4 := cast_4 * xBuffer_temp(5);
      add_cast_10 := resize(mul_temp_4, 73);
      add_temp_4 := add_cast_9 + add_cast_10;
      IF ((add_temp_4(72) = '0') AND (add_temp_4(71 DOWNTO 70) /= "00")) OR ((add_temp_4(72) = '0') AND (add_temp_4(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(5) := X"7FFFFF";
      ELSIF (add_temp_4(72) = '1') AND (add_temp_4(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(5) := X"800000";
      ELSE 
        wBuffer_temp(5) := add_temp_4(70 DOWNTO 47) + ('0' & add_temp_4(46));
      END IF;
      add_cast_11 := resize(wBuffer(6) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast_5 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_5 := cast_5 * xBuffer_temp(6);
      add_cast_12 := resize(mul_temp_5, 73);
      add_temp_5 := add_cast_11 + add_cast_12;
      IF ((add_temp_5(72) = '0') AND (add_temp_5(71 DOWNTO 70) /= "00")) OR ((add_temp_5(72) = '0') AND (add_temp_5(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(6) := X"7FFFFF";
      ELSIF (add_temp_5(72) = '1') AND (add_temp_5(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(6) := X"800000";
      ELSE 
        wBuffer_temp(6) := add_temp_5(70 DOWNTO 47) + ('0' & add_temp_5(46));
      END IF;
      add_cast_13 := resize(wBuffer(7) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast_6 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_6 := cast_6 * xBuffer_temp(7);
      add_cast_14 := resize(mul_temp_6, 73);
      add_temp_6 := add_cast_13 + add_cast_14;
      IF ((add_temp_6(72) = '0') AND (add_temp_6(71 DOWNTO 70) /= "00")) OR ((add_temp_6(72) = '0') AND (add_temp_6(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(7) := X"7FFFFF";
      ELSIF (add_temp_6(72) = '1') AND (add_temp_6(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(7) := X"800000";
      ELSE 
        wBuffer_temp(7) := add_temp_6(70 DOWNTO 47) + ('0' & add_temp_6(46));
      END IF;
      add_cast_15 := resize(wBuffer(8) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast_7 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_7 := cast_7 * xBuffer_temp(8);
      add_cast_16 := resize(mul_temp_7, 73);
      add_temp_7 := add_cast_15 + add_cast_16;
      IF ((add_temp_7(72) = '0') AND (add_temp_7(71 DOWNTO 70) /= "00")) OR ((add_temp_7(72) = '0') AND (add_temp_7(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(8) := X"7FFFFF";
      ELSIF (add_temp_7(72) = '1') AND (add_temp_7(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(8) := X"800000";
      ELSE 
        wBuffer_temp(8) := add_temp_7(70 DOWNTO 47) + ('0' & add_temp_7(46));
      END IF;
      add_cast_17 := resize(wBuffer(9) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast_8 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_8 := cast_8 * xBuffer_temp(9);
      add_cast_18 := resize(mul_temp_8, 73);
      add_temp_8 := add_cast_17 + add_cast_18;
      IF ((add_temp_8(72) = '0') AND (add_temp_8(71 DOWNTO 70) /= "00")) OR ((add_temp_8(72) = '0') AND (add_temp_8(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(9) := X"7FFFFF";
      ELSIF (add_temp_8(72) = '1') AND (add_temp_8(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(9) := X"800000";
      ELSE 
        wBuffer_temp(9) := add_temp_8(70 DOWNTO 47) + ('0' & add_temp_8(46));
      END IF;
      add_cast_19 := resize(wBuffer(10) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast_9 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_9 := cast_9 * xBuffer_temp(10);
      add_cast_20 := resize(mul_temp_9, 73);
      add_temp_9 := add_cast_19 + add_cast_20;
      IF ((add_temp_9(72) = '0') AND (add_temp_9(71 DOWNTO 70) /= "00")) OR ((add_temp_9(72) = '0') AND (add_temp_9(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(10) := X"7FFFFF";
      ELSIF (add_temp_9(72) = '1') AND (add_temp_9(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(10) := X"800000";
      ELSE 
        wBuffer_temp(10) := add_temp_9(70 DOWNTO 47) + ('0' & add_temp_9(46));
      END IF;
      add_cast_21 := resize(wBuffer(11) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 73);
      cast_10 := resize(E_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 48);
      mul_temp_10 := cast_10 * xBuffer_temp(11);
      add_cast_22 := resize(mul_temp_10, 73);
      add_temp_10 := add_cast_21 + add_cast_22;
      IF ((add_temp_10(72) = '0') AND (add_temp_10(71 DOWNTO 70) /= "00")) OR ((add_temp_10(72) = '0') AND (add_temp_10(70 DOWNTO 47) = X"7FFFFF")) THEN 
        wBuffer_temp(11) := X"7FFFFF";
      ELSIF (add_temp_10(72) = '1') AND (add_temp_10(71 DOWNTO 70) /= "11") THEN 
        wBuffer_temp(11) := X"800000";
      ELSE 
        wBuffer_temp(11) := add_temp_10(70 DOWNTO 47) + ('0' & add_temp_10(46));
      END IF;
      --         wBuffer(:) = (wBuffer) + 0.5*E*(xBuffer);
    END IF;

    W_tmp <= wBuffer_temp;
    xBuffer_next <= xBuffer_temp;
    wBuffer_next <= wBuffer_temp;
  END PROCESS LMSUpdate_1_output;

  outputgen: FOR k IN 0 TO 11 GENERATE
    W(k) <= std_logic_vector(W_tmp(k));
  END GENERATE;

END rtl;

