-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\nlms_filter\Subsystem.vhd
-- Created: 2020-10-16 22:13:02
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.2
-- Out2                          ce_out        0.2
-- Out3                          ce_out        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: nlms_filter/Subsystem
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.top_level_pkg.ALL;

ENTITY LMSFilter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24 INPUT SIGNAL
        In2                               :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24 DESIRED SIGNAL
        ce_out                            :   OUT   std_logic;
        --Out1                              :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24
        --Out2                              :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24
        Out3                              :   OUT   vector_of_std_logic_vector24(0 TO 11)  -- sfix24_En23 [12] WEIGHTS
        );
END LMSFilter;


ARCHITECTURE rtl OF LMSFilter IS

  -- Constants
  CONSTANT C_LMS_FILTER_LEAKAGE           : signed(15 DOWNTO 0) := 
    "0111111111111111";  -- sfix16_En15
  CONSTANT C_LMS_FILTER_STEP_SIZE         : signed(15 DOWNTO 0) := 
    "0000000001000000";  -- sfix16_En15
  
  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In1_signed                       : signed(23 DOWNTO 0):= (others => '0');  -- sfix24
  SIGNAL In2_signed                       : signed(23 DOWNTO 0):= (others => '0');  -- sfix24
  SIGNAL LMS_Filter_out1                  : signed(23 DOWNTO 0):= (others => '0');  -- sfix24
  SIGNAL LMS_Filter_out2                  : signed(23 DOWNTO 0):= (others => '0');  -- sfix24
  SIGNAL LMS_Filter_out3                  : vector_of_signed24(0 TO 11):= (others => (others => '0'));  -- sfix24_En23 [12]
  SIGNAL weight                           : vector_of_signed24(0 TO 11):= (others => (others => '0'));  -- sfix24_En23 [12]
  SIGNAL filter_sum                       : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL data_pipeline                    : vector_of_signed24(0 TO 11):= (others => (others => '0'));  -- sfix24 [12]
  SIGNAL data_pipeline_tmp                : vector_of_signed24(0 TO 10):= (others => (others => '0'));  -- sfix24 [11]
  SIGNAL filter_products                  : vector_of_signed32(0 TO 11):= (others => (others => '0'));  -- sfix32_En20 [12]
  SIGNAL mul_temp                         : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL mul_temp_1                       : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL mul_temp_2                       : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL mul_temp_3                       : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL mul_temp_4                       : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL mul_temp_5                       : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL mul_temp_6                       : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL mul_temp_7                       : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL mul_temp_8                       : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL mul_temp_9                       : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL mul_temp_10                      : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL mul_temp_11                      : signed(47 DOWNTO 0):= (others => '0');  -- sfix48_En23
  SIGNAL sum_1                            : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast                         : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_1                       : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp                         : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL sum_2                            : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_2                       : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_3                       : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_1                       : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL sum_3                            : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_4                       : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_5                       : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_2                       : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL sum_4                            : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_6                       : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_7                       : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_3                       : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL sum_5                            : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_8                       : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_9                       : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_4                       : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL sum_6                            : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_10                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_11                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_5                       : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL sum_7                            : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_12                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_13                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_6                       : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL sum_8                            : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_14                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_15                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_7                       : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL sum_9                            : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_16                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_17                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_8                       : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL sum_10                           : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_18                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_19                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_9                       : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL add_cast_20                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_21                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_10                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL sub_cast                         : signed(23 DOWNTO 0):= (others => '0');  -- sfix24
  SIGNAL sub_cast_1                       : signed(23 DOWNTO 0):= (others => '0');  -- sfix24
  SIGNAL sub_temp                         : signed(24 DOWNTO 0):= (others => '0');  -- sfix25
  SIGNAL mu_err                           : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL mul_temp_12                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En15
  SIGNAL mu_err_data_prod                 : vector_of_signed32(0 TO 11):= (others => (others => '0'));  -- sfix32_En20 [12]
  SIGNAL mul_temp_13                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL mul_temp_14                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL mul_temp_15                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL mul_temp_16                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL mul_temp_17                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL mul_temp_18                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL mul_temp_19                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL mul_temp_20                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL mul_temp_21                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL mul_temp_22                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL mul_temp_23                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL mul_temp_24                      : signed(55 DOWNTO 0):= (others => '0');  -- sfix56_En20
  SIGNAL weight_scaled                    : vector_of_signed32(0 TO 11):= (others => (others => '0'));  -- sfix32_En20 [12]
  SIGNAL weight_adder_output              : vector_of_signed32(0 TO 11):= (others => (others => '0'));  -- sfix32_En20 [12]
  SIGNAL weight_adder_output_cast         : vector_of_signed24(0 TO 11):= (others => (others => '0'));  -- sfix24_En23 [12]
  SIGNAL add_cast_22                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_23                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_11                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_25                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38
  SIGNAL add_cast_24                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_25                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_12                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_26                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38
  SIGNAL add_cast_26                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_27                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_13                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_27                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38
  SIGNAL add_cast_28                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_29                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_14                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_28                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38
  SIGNAL add_cast_30                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_31                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_15                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_29                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38
  SIGNAL add_cast_32                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_33                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_16                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_30                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38
  SIGNAL add_cast_34                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_35                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_17                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_31                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38
  SIGNAL add_cast_36                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_37                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_18                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_32                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38
  SIGNAL add_cast_38                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_39                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_19                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_33                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38
  SIGNAL add_cast_40                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_41                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_20                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_34                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38
  SIGNAL add_cast_42                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_43                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_21                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_35                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38
  SIGNAL add_cast_44                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_cast_45                      : signed(31 DOWNTO 0):= (others => '0');  -- sfix32_En20
  SIGNAL add_temp_22                      : signed(32 DOWNTO 0):= (others => '0');  -- sfix33_En20
  SIGNAL mul_temp_36                      : signed(39 DOWNTO 0):= (others => '0');  -- sfix40_En38

BEGIN
  In1_signed <= signed(In1);

  In2_signed <= signed(In2);

  enb <= clk_enable;


-- ***********************
-- ********* LMS *********
-- ***********************

-- * LMS: FIR section

  LMS_Filter_del_temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      data_pipeline_tmp <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        data_pipeline_tmp(0 TO 9) <= data_pipeline_tmp(1 TO 10);
        data_pipeline_tmp(10) <= In1_signed;
      END IF;
    END IF;
  END PROCESS LMS_Filter_del_temp_process1;

  data_pipeline(0 TO 10) <= data_pipeline_tmp(0 TO 10);
  data_pipeline(11) <= In1_signed;

  mul_temp <= data_pipeline(0) * weight(0);
  filter_products(0) <= mul_temp(34 DOWNTO 3);

  mul_temp_1 <= data_pipeline(1) * weight(1);
  filter_products(1) <= mul_temp_1(34 DOWNTO 3);

  mul_temp_2 <= data_pipeline(2) * weight(2);
  filter_products(2) <= mul_temp_2(34 DOWNTO 3);

  mul_temp_3 <= data_pipeline(3) * weight(3);
  filter_products(3) <= mul_temp_3(34 DOWNTO 3);

  mul_temp_4 <= data_pipeline(4) * weight(4);
  filter_products(4) <= mul_temp_4(34 DOWNTO 3);

  mul_temp_5 <= data_pipeline(5) * weight(5);
  filter_products(5) <= mul_temp_5(34 DOWNTO 3);

  mul_temp_6 <= data_pipeline(6) * weight(6);
  filter_products(6) <= mul_temp_6(34 DOWNTO 3);

  mul_temp_7 <= data_pipeline(7) * weight(7);
  filter_products(7) <= mul_temp_7(34 DOWNTO 3);

  mul_temp_8 <= data_pipeline(8) * weight(8);
  filter_products(8) <= mul_temp_8(34 DOWNTO 3);

  mul_temp_9 <= data_pipeline(9) * weight(9);
  filter_products(9) <= mul_temp_9(34 DOWNTO 3);

  mul_temp_10 <= data_pipeline(10) * weight(10);
  filter_products(10) <= mul_temp_10(34 DOWNTO 3);

  mul_temp_11 <= data_pipeline(11) * weight(11);
  filter_products(11) <= mul_temp_11(34 DOWNTO 3);

-- linear sum of filter products

  add_cast <= filter_products(0);
  add_cast_1 <= filter_products(1);
  add_temp <= resize(add_cast, 33) + resize(add_cast_1, 33);
  sum_1 <= add_temp(31 DOWNTO 0);

  add_cast_2 <= sum_1;
  add_cast_3 <= filter_products(2);
  add_temp_1 <= resize(add_cast_2, 33) + resize(add_cast_3, 33);
  sum_2 <= add_temp_1(31 DOWNTO 0);

  add_cast_4 <= sum_2;
  add_cast_5 <= filter_products(3);
  add_temp_2 <= resize(add_cast_4, 33) + resize(add_cast_5, 33);
  sum_3 <= add_temp_2(31 DOWNTO 0);

  add_cast_6 <= sum_3;
  add_cast_7 <= filter_products(4);
  add_temp_3 <= resize(add_cast_6, 33) + resize(add_cast_7, 33);
  sum_4 <= add_temp_3(31 DOWNTO 0);

  add_cast_8 <= sum_4;
  add_cast_9 <= filter_products(5);
  add_temp_4 <= resize(add_cast_8, 33) + resize(add_cast_9, 33);
  sum_5 <= add_temp_4(31 DOWNTO 0);

  add_cast_10 <= sum_5;
  add_cast_11 <= filter_products(6);
  add_temp_5 <= resize(add_cast_10, 33) + resize(add_cast_11, 33);
  sum_6 <= add_temp_5(31 DOWNTO 0);

  add_cast_12 <= sum_6;
  add_cast_13 <= filter_products(7);
  add_temp_6 <= resize(add_cast_12, 33) + resize(add_cast_13, 33);
  sum_7 <= add_temp_6(31 DOWNTO 0);

  add_cast_14 <= sum_7;
  add_cast_15 <= filter_products(8);
  add_temp_7 <= resize(add_cast_14, 33) + resize(add_cast_15, 33);
  sum_8 <= add_temp_7(31 DOWNTO 0);

  add_cast_16 <= sum_8;
  add_cast_17 <= filter_products(9);
  add_temp_8 <= resize(add_cast_16, 33) + resize(add_cast_17, 33);
  sum_9 <= add_temp_8(31 DOWNTO 0);

  add_cast_18 <= sum_9;
  add_cast_19 <= filter_products(10);
  add_temp_9 <= resize(add_cast_18, 33) + resize(add_cast_19, 33);
  sum_10 <= add_temp_9(31 DOWNTO 0);

  add_cast_20 <= sum_10;
  add_cast_21 <= filter_products(11);
  add_temp_10 <= resize(add_cast_20, 33) + resize(add_cast_21, 33);
  filter_sum <= add_temp_10(31 DOWNTO 0);

  LMS_Filter_out1 <= resize(filter_sum(31 DOWNTO 20), 24);

-- * Calculate Filter Error

  sub_cast <= In2_signed;
  sub_cast_1 <= resize(filter_sum(31 DOWNTO 20), 24);
  sub_temp <= resize(sub_cast, 25) - resize(sub_cast_1, 25);
  LMS_Filter_out2 <= sub_temp(23 DOWNTO 0);

-- ***** LMS Weight Update Function *****

  mul_temp_12 <= C_LMS_FILTER_STEP_SIZE * LMS_Filter_out2;
  mu_err <= resize(mul_temp_12(26 DOWNTO 0) & '0' & '0' & '0' & '0' & '0', 32);

  mul_temp_13 <= data_pipeline(0) * mu_err;
  mu_err_data_prod(0) <= mul_temp_13(31 DOWNTO 0);

  mul_temp_14 <= data_pipeline(1) * mu_err;
  mu_err_data_prod(1) <= mul_temp_14(31 DOWNTO 0);

  mul_temp_15 <= data_pipeline(2) * mu_err;
  mu_err_data_prod(2) <= mul_temp_15(31 DOWNTO 0);

  mul_temp_16 <= data_pipeline(3) * mu_err;
  mu_err_data_prod(3) <= mul_temp_16(31 DOWNTO 0);

  mul_temp_17 <= data_pipeline(4) * mu_err;
  mu_err_data_prod(4) <= mul_temp_17(31 DOWNTO 0);

  mul_temp_18 <= data_pipeline(5) * mu_err;
  mu_err_data_prod(5) <= mul_temp_18(31 DOWNTO 0);

  mul_temp_19 <= data_pipeline(6) * mu_err;
  mu_err_data_prod(6) <= mul_temp_19(31 DOWNTO 0);

  mul_temp_20 <= data_pipeline(7) * mu_err;
  mu_err_data_prod(7) <= mul_temp_20(31 DOWNTO 0);

  mul_temp_21 <= data_pipeline(8) * mu_err;
  mu_err_data_prod(8) <= mul_temp_21(31 DOWNTO 0);

  mul_temp_22 <= data_pipeline(9) * mu_err;
  mu_err_data_prod(9) <= mul_temp_22(31 DOWNTO 0);

  mul_temp_23 <= data_pipeline(10) * mu_err;
  mu_err_data_prod(10) <= mul_temp_23(31 DOWNTO 0);

  mul_temp_24 <= data_pipeline(11) * mu_err;
  mu_err_data_prod(11) <= mul_temp_24(31 DOWNTO 0);

-- * LMS_Filter Weight Accumulator

  add_cast_22 <= weight_scaled(0);
  add_cast_23 <= mu_err_data_prod(0);
  add_temp_11 <= resize(add_cast_22, 33) + resize(add_cast_23, 33);
  weight_adder_output(0) <= add_temp_11(31 DOWNTO 0);

  mul_temp_25 <= C_LMS_FILTER_LEAKAGE * weight(0);
  weight_scaled(0) <= resize(mul_temp_25(39 DOWNTO 18), 32);

  add_cast_24 <= weight_scaled(1);
  add_cast_25 <= mu_err_data_prod(1);
  add_temp_12 <= resize(add_cast_24, 33) + resize(add_cast_25, 33);
  weight_adder_output(1) <= add_temp_12(31 DOWNTO 0);

  mul_temp_26 <= C_LMS_FILTER_LEAKAGE * weight(1);
  weight_scaled(1) <= resize(mul_temp_26(39 DOWNTO 18), 32);

  add_cast_26 <= weight_scaled(2);
  add_cast_27 <= mu_err_data_prod(2);
  add_temp_13 <= resize(add_cast_26, 33) + resize(add_cast_27, 33);
  weight_adder_output(2) <= add_temp_13(31 DOWNTO 0);

  mul_temp_27 <= C_LMS_FILTER_LEAKAGE * weight(2);
  weight_scaled(2) <= resize(mul_temp_27(39 DOWNTO 18), 32);

  add_cast_28 <= weight_scaled(3);
  add_cast_29 <= mu_err_data_prod(3);
  add_temp_14 <= resize(add_cast_28, 33) + resize(add_cast_29, 33);
  weight_adder_output(3) <= add_temp_14(31 DOWNTO 0);

  mul_temp_28 <= C_LMS_FILTER_LEAKAGE * weight(3);
  weight_scaled(3) <= resize(mul_temp_28(39 DOWNTO 18), 32);

  add_cast_30 <= weight_scaled(4);
  add_cast_31 <= mu_err_data_prod(4);
  add_temp_15 <= resize(add_cast_30, 33) + resize(add_cast_31, 33);
  weight_adder_output(4) <= add_temp_15(31 DOWNTO 0);

  mul_temp_29 <= C_LMS_FILTER_LEAKAGE * weight(4);
  weight_scaled(4) <= resize(mul_temp_29(39 DOWNTO 18), 32);

  add_cast_32 <= weight_scaled(5);
  add_cast_33 <= mu_err_data_prod(5);
  add_temp_16 <= resize(add_cast_32, 33) + resize(add_cast_33, 33);
  weight_adder_output(5) <= add_temp_16(31 DOWNTO 0);

  mul_temp_30 <= C_LMS_FILTER_LEAKAGE * weight(5);
  weight_scaled(5) <= resize(mul_temp_30(39 DOWNTO 18), 32);

  add_cast_34 <= weight_scaled(6);
  add_cast_35 <= mu_err_data_prod(6);
  add_temp_17 <= resize(add_cast_34, 33) + resize(add_cast_35, 33);
  weight_adder_output(6) <= add_temp_17(31 DOWNTO 0);

  mul_temp_31 <= C_LMS_FILTER_LEAKAGE * weight(6);
  weight_scaled(6) <= resize(mul_temp_31(39 DOWNTO 18), 32);

  add_cast_36 <= weight_scaled(7);
  add_cast_37 <= mu_err_data_prod(7);
  add_temp_18 <= resize(add_cast_36, 33) + resize(add_cast_37, 33);
  weight_adder_output(7) <= add_temp_18(31 DOWNTO 0);

  mul_temp_32 <= C_LMS_FILTER_LEAKAGE * weight(7);
  weight_scaled(7) <= resize(mul_temp_32(39 DOWNTO 18), 32);

  add_cast_38 <= weight_scaled(8);
  add_cast_39 <= mu_err_data_prod(8);
  add_temp_19 <= resize(add_cast_38, 33) + resize(add_cast_39, 33);
  weight_adder_output(8) <= add_temp_19(31 DOWNTO 0);

  mul_temp_33 <= C_LMS_FILTER_LEAKAGE * weight(8);
  weight_scaled(8) <= resize(mul_temp_33(39 DOWNTO 18), 32);

  add_cast_40 <= weight_scaled(9);
  add_cast_41 <= mu_err_data_prod(9);
  add_temp_20 <= resize(add_cast_40, 33) + resize(add_cast_41, 33);
  weight_adder_output(9) <= add_temp_20(31 DOWNTO 0);

  mul_temp_34 <= C_LMS_FILTER_LEAKAGE * weight(9);
  weight_scaled(9) <= resize(mul_temp_34(39 DOWNTO 18), 32);

  add_cast_42 <= weight_scaled(10);
  add_cast_43 <= mu_err_data_prod(10);
  add_temp_21 <= resize(add_cast_42, 33) + resize(add_cast_43, 33);
  weight_adder_output(10) <= add_temp_21(31 DOWNTO 0);

  mul_temp_35 <= C_LMS_FILTER_LEAKAGE * weight(10);
  weight_scaled(10) <= resize(mul_temp_35(39 DOWNTO 18), 32);

  add_cast_44 <= weight_scaled(11);
  add_cast_45 <= mu_err_data_prod(11);
  add_temp_22 <= resize(add_cast_44, 33) + resize(add_cast_45, 33);
  weight_adder_output(11) <= add_temp_22(31 DOWNTO 0);

  mul_temp_36 <= C_LMS_FILTER_LEAKAGE * weight(11);
  weight_scaled(11) <= resize(mul_temp_36(39 DOWNTO 18), 32);

  weight_adder_output_cast_gen:FOR k IN 0 TO 11 GENERATE
    weight_adder_output_cast(k) <= resize(weight_adder_output(k)(20 DOWNTO 0) & '0' & '0' & '0', 24);
  END GENERATE;

  LMS_Filter_acc_temp_process2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      weight <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        weight(0 TO 11) <= weight_adder_output_cast(0 TO 11);
      END IF;
    END IF;
  END PROCESS LMS_Filter_acc_temp_process2;

-- * LMS_Filter Weight Output Port

  LMS_Filter_out3(11) <= weight_adder_output_cast(0);
  LMS_Filter_out3(10) <= weight_adder_output_cast(1);
  LMS_Filter_out3(9) <= weight_adder_output_cast(2);
  LMS_Filter_out3(8) <= weight_adder_output_cast(3);
  LMS_Filter_out3(7) <= weight_adder_output_cast(4);
  LMS_Filter_out3(6) <= weight_adder_output_cast(5);
  LMS_Filter_out3(5) <= weight_adder_output_cast(6);
  LMS_Filter_out3(4) <= weight_adder_output_cast(7);
  LMS_Filter_out3(3) <= weight_adder_output_cast(8);
  LMS_Filter_out3(2) <= weight_adder_output_cast(9);
  LMS_Filter_out3(1) <= weight_adder_output_cast(10);
  LMS_Filter_out3(0) <= weight_adder_output_cast(11);


  --Out1 <= std_logic_vector(LMS_Filter_out1);

  --Out2 <= std_logic_vector(LMS_Filter_out2);

  outputgen: FOR k IN 0 TO 11 GENERATE
    Out3(k) <= std_logic_vector(LMS_Filter_out3(k));
  END GENERATE;

  ce_out <= clk_enable;

END rtl;

