-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\untitled3\nlmsUpdateSystem.vhd
-- Created: 2020-10-17 22:41:18
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.001
-- Target subsystem base rate: 0.001
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.001
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- weights                       ce_out        0.001
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: nlmsUpdateSystem
-- Source Path: untitled3/nlmsUpdateSystem
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.top_level_pkg.ALL;

ENTITY nlmsUpdateSystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        input                             :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24
        error_rsvd                        :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24
        adapt                             :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        weights                           :   OUT   vector_of_std_logic_vector24(0 TO 11)  -- sfix24_En23 [12]
        );
END nlmsUpdateSystem;


ARCHITECTURE rtl OF nlmsUpdateSystem IS

  -- Component Declarations
  COMPONENT nlmsUpdate
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          X                               :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24
          E                               :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24
          Adapt                           :   IN    std_logic;
          W                               :   OUT   vector_of_std_logic_vector24(0 TO 11)  -- sfix24_En23 [12]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nlmsUpdate
    USE ENTITY work.nlmsUpdate(rtl);

  -- Signals
  SIGNAL W                                : vector_of_std_logic_vector24(0 TO 11);  -- ufix24 [12]

BEGIN
  u_nlmsUpdate : nlmsUpdate
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              X => input,  -- sfix24
              E => error_rsvd,  -- sfix24
              Adapt => adapt,
              W => W  -- sfix24_En23 [12]
              );

  ce_out <= clk_enable;

  weights <= W;

END rtl;

