-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\sine_wave\sine_generator.vhd
-- Created: 2020-10-23 21:09:46
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.0001
-- Target subsystem base rate: 0.0001
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sine_generator
-- Source Path: sine_wave/sine_generator
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY sine_generator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24
        );
END sine_generator;


ARCHITECTURE rtl OF sine_generator IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Sine_Wave_out1                   : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL address_cnt                      : unsigned(6 DOWNTO 0) := (others => '0');  -- ufix7

BEGIN
  enb <= clk_enable;

-- ADDRESS COUNTER
  Sine_Wave_addrcnt_temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      address_cnt <= to_unsigned(0, 7);
    ELSIF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF address_cnt >= to_unsigned(99, 7) THEN
          address_cnt <= to_unsigned(0, 7);
        ELSE
          address_cnt <= address_cnt + to_unsigned(1, 7);
        END IF;
      END IF;
    END IF; 
  END PROCESS Sine_Wave_addrcnt_temp_process1;

-- FULL WAVE LOOKUP TABLE
  PROCESS(address_cnt)
  BEGIN
    CASE address_cnt IS
      WHEN "0000000" => Sine_Wave_out1 <= "000000000000000000000000";
      WHEN "0000001" => Sine_Wave_out1 <= "000000000000010011101000";
      WHEN "0000010" => Sine_Wave_out1 <= "000000000000100111001011";
      WHEN "0000011" => Sine_Wave_out1 <= "000000000000111010100100";
      WHEN "0000100" => Sine_Wave_out1 <= "000000000001001101101110";
      WHEN "0000101" => Sine_Wave_out1 <= "000000000001100000100100";
      WHEN "0000110" => Sine_Wave_out1 <= "000000000001110011000010";
      WHEN "0000111" => Sine_Wave_out1 <= "000000000010000101000100";
      WHEN "0001000" => Sine_Wave_out1 <= "000000000010010110100011";
      WHEN "0001001" => Sine_Wave_out1 <= "000000000010100111011101";
      WHEN "0001010" => Sine_Wave_out1 <= "000000000010110111101100";
      WHEN "0001011" => Sine_Wave_out1 <= "000000000011000111001100";
      WHEN "0001100" => Sine_Wave_out1 <= "000000000011010101111011";
      WHEN "0001101" => Sine_Wave_out1 <= "000000000011100011110011";
      WHEN "0001110" => Sine_Wave_out1 <= "000000000011110000110010";
      WHEN "0001111" => Sine_Wave_out1 <= "000000000011111100110100";
      WHEN "0010000" => Sine_Wave_out1 <= "000000000100000111110111";
      WHEN "0010001" => Sine_Wave_out1 <= "000000000100010001110110";
      WHEN "0010010" => Sine_Wave_out1 <= "000000000100011010110001";
      WHEN "0010011" => Sine_Wave_out1 <= "000000000100100010100100";
      WHEN "0010100" => Sine_Wave_out1 <= "000000000100101001001101";
      WHEN "0010101" => Sine_Wave_out1 <= "000000000100101110101100";
      WHEN "0010110" => Sine_Wave_out1 <= "000000000100110010111110";
      WHEN "0010111" => Sine_Wave_out1 <= "000000000100110110000010";
      WHEN "0011000" => Sine_Wave_out1 <= "000000000100110111111001";
      WHEN "0011001" => Sine_Wave_out1 <= "000000000100111000100000";
      WHEN "0011010" => Sine_Wave_out1 <= "000000000100110111111001";
      WHEN "0011011" => Sine_Wave_out1 <= "000000000100110110000010";
      WHEN "0011100" => Sine_Wave_out1 <= "000000000100110010111110";
      WHEN "0011101" => Sine_Wave_out1 <= "000000000100101110101100";
      WHEN "0011110" => Sine_Wave_out1 <= "000000000100101001001101";
      WHEN "0011111" => Sine_Wave_out1 <= "000000000100100010100100";
      WHEN "0100000" => Sine_Wave_out1 <= "000000000100011010110001";
      WHEN "0100001" => Sine_Wave_out1 <= "000000000100010001110110";
      WHEN "0100010" => Sine_Wave_out1 <= "000000000100000111110111";
      WHEN "0100011" => Sine_Wave_out1 <= "000000000011111100110100";
      WHEN "0100100" => Sine_Wave_out1 <= "000000000011110000110010";
      WHEN "0100101" => Sine_Wave_out1 <= "000000000011100011110011";
      WHEN "0100110" => Sine_Wave_out1 <= "000000000011010101111011";
      WHEN "0100111" => Sine_Wave_out1 <= "000000000011000111001100";
      WHEN "0101000" => Sine_Wave_out1 <= "000000000010110111101100";
      WHEN "0101001" => Sine_Wave_out1 <= "000000000010100111011101";
      WHEN "0101010" => Sine_Wave_out1 <= "000000000010010110100011";
      WHEN "0101011" => Sine_Wave_out1 <= "000000000010000101000100";
      WHEN "0101100" => Sine_Wave_out1 <= "000000000001110011000010";
      WHEN "0101101" => Sine_Wave_out1 <= "000000000001100000100100";
      WHEN "0101110" => Sine_Wave_out1 <= "000000000001001101101110";
      WHEN "0101111" => Sine_Wave_out1 <= "000000000000111010100100";
      WHEN "0110000" => Sine_Wave_out1 <= "000000000000100111001011";
      WHEN "0110001" => Sine_Wave_out1 <= "000000000000010011101000";
      WHEN "0110010" => Sine_Wave_out1 <= "000000000000000000000000";
      WHEN "0110011" => Sine_Wave_out1 <= "111111111111101100011000";
      WHEN "0110100" => Sine_Wave_out1 <= "111111111111011000110101";
      WHEN "0110101" => Sine_Wave_out1 <= "111111111111000101011100";
      WHEN "0110110" => Sine_Wave_out1 <= "111111111110110010010010";
      WHEN "0110111" => Sine_Wave_out1 <= "111111111110011111011100";
      WHEN "0111000" => Sine_Wave_out1 <= "111111111110001100111110";
      WHEN "0111001" => Sine_Wave_out1 <= "111111111101111010111100";
      WHEN "0111010" => Sine_Wave_out1 <= "111111111101101001011101";
      WHEN "0111011" => Sine_Wave_out1 <= "111111111101011000100011";
      WHEN "0111100" => Sine_Wave_out1 <= "111111111101001000010100";
      WHEN "0111101" => Sine_Wave_out1 <= "111111111100111000110100";
      WHEN "0111110" => Sine_Wave_out1 <= "111111111100101010000101";
      WHEN "0111111" => Sine_Wave_out1 <= "111111111100011100001101";
      WHEN "1000000" => Sine_Wave_out1 <= "111111111100001111001110";
      WHEN "1000001" => Sine_Wave_out1 <= "111111111100000011001100";
      WHEN "1000010" => Sine_Wave_out1 <= "111111111011111000001001";
      WHEN "1000011" => Sine_Wave_out1 <= "111111111011101110001010";
      WHEN "1000100" => Sine_Wave_out1 <= "111111111011100101001111";
      WHEN "1000101" => Sine_Wave_out1 <= "111111111011011101011100";
      WHEN "1000110" => Sine_Wave_out1 <= "111111111011010110110011";
      WHEN "1000111" => Sine_Wave_out1 <= "111111111011010001010100";
      WHEN "1001000" => Sine_Wave_out1 <= "111111111011001101000010";
      WHEN "1001001" => Sine_Wave_out1 <= "111111111011001001111110";
      WHEN "1001010" => Sine_Wave_out1 <= "111111111011001000000111";
      WHEN "1001011" => Sine_Wave_out1 <= "111111111011000111100000";
      WHEN "1001100" => Sine_Wave_out1 <= "111111111011001000000111";
      WHEN "1001101" => Sine_Wave_out1 <= "111111111011001001111110";
      WHEN "1001110" => Sine_Wave_out1 <= "111111111011001101000010";
      WHEN "1001111" => Sine_Wave_out1 <= "111111111011010001010100";
      WHEN "1010000" => Sine_Wave_out1 <= "111111111011010110110011";
      WHEN "1010001" => Sine_Wave_out1 <= "111111111011011101011100";
      WHEN "1010010" => Sine_Wave_out1 <= "111111111011100101001111";
      WHEN "1010011" => Sine_Wave_out1 <= "111111111011101110001010";
      WHEN "1010100" => Sine_Wave_out1 <= "111111111011111000001001";
      WHEN "1010101" => Sine_Wave_out1 <= "111111111100000011001100";
      WHEN "1010110" => Sine_Wave_out1 <= "111111111100001111001110";
      WHEN "1010111" => Sine_Wave_out1 <= "111111111100011100001101";
      WHEN "1011000" => Sine_Wave_out1 <= "111111111100101010000101";
      WHEN "1011001" => Sine_Wave_out1 <= "111111111100111000110100";
      WHEN "1011010" => Sine_Wave_out1 <= "111111111101001000010100";
      WHEN "1011011" => Sine_Wave_out1 <= "111111111101011000100011";
      WHEN "1011100" => Sine_Wave_out1 <= "111111111101101001011101";
      WHEN "1011101" => Sine_Wave_out1 <= "111111111101111010111100";
      WHEN "1011110" => Sine_Wave_out1 <= "111111111110001100111110";
      WHEN "1011111" => Sine_Wave_out1 <= "111111111110011111011100";
      WHEN "1100000" => Sine_Wave_out1 <= "111111111110110010010010";
      WHEN "1100001" => Sine_Wave_out1 <= "111111111111000101011100";
      WHEN "1100010" => Sine_Wave_out1 <= "111111111111011000110101";
      WHEN "1100011" => Sine_Wave_out1 <= "111111111111101100011000";
      WHEN OTHERS => Sine_Wave_out1 <= "111111111111101100011000";
    END CASE;
  END PROCESS;


  Out1 <= std_logic_vector(Sine_Wave_out1);

  ce_out <= clk_enable;

END rtl;

