-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fir_filter_hdl_optimized_12\subFilter_12.vhd
-- Created: 2020-11-19 01:58:56
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: subFilter_12
-- Source Path: fir_filter_hdl_optimized_12/Subsystem_12/Discrete FIR Filter HDL Optimized 12/FilterBank/subFilter_12
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.top_level_pkg.ALL;

ENTITY subFilter_12 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        coefIn                            :   IN    vector_of_std_logic_vector24(0 TO 11);  -- sfix24_En24 [12]
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dout_1_re                         :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        doutVld                           :   OUT   std_logic
        );
END subFilter_12;


ARCHITECTURE rtl OF subFilter_12 IS

  -- Component Declarations
  COMPONENT FilterTapSystolicWvldin_12
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
          coefIn_0                        :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
          addin                           :   IN    std_logic_vector(51 DOWNTO 0);  -- sfix52_En48
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
          tapout                          :   OUT   std_logic_vector(51 DOWNTO 0)  -- sfix52_En48
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterTapSystolicWvldin_12
    USE ENTITY work.FilterTapSystolicWvldin_12(rtl);

  -- Signals
  SIGNAL intdelay_reg                     : std_logic_vector(0 TO 14);  -- ufix1 [15]
  SIGNAL vldShift                         : std_logic;
  SIGNAL vldOutTmp                        : std_logic;
  SIGNAL ZERO_OUT                         : signed(23 DOWNTO 0);  -- sfix24_En24
  SIGNAL addin                            : signed(51 DOWNTO 0);  -- sfix52_En48
  SIGNAL dinDly2                          : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout                           : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL dinDly                           : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_1                         : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL dinDly_1                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_2                         : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL dinDly_2                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_3                         : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL dinDly_3                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_4                         : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL dinDly_4                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_5                         : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL dinDly_5                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_6                         : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL dinDly_6                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_7                         : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL dinDly_7                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_8                         : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL dinDly_8                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_9                         : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL dinDly_9                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_10                        : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL dinDly_10                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_11                        : std_logic_vector(51 DOWNTO 0);  -- ufix52
  SIGNAL tapout_signed                    : signed(51 DOWNTO 0);  -- sfix52_En48
  SIGNAL dout_cast                        : signed(23 DOWNTO 0);  -- sfix24_En24
  SIGNAL muxOut                           : signed(23 DOWNTO 0);  -- sfix24_En24
  SIGNAL dout_1_re_tmp                    : signed(23 DOWNTO 0);  -- sfix24_En24

BEGIN
  u_FilterTap_1 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix24_En24
              coefIn_0 => coefIn(0),  -- sfix24_En24
              addin => std_logic_vector(addin),  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2,  -- sfix24_En24
              tapout => tapout  -- sfix52_En48
              );

  u_FilterTap_2 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2,  -- sfix24_En24
              coefIn_0 => coefIn(1),  -- sfix24_En24
              addin => tapout,  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly,  -- sfix24_En24
              tapout => tapout_1  -- sfix52_En48
              );

  u_FilterTap_3 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly,  -- sfix24_En24
              coefIn_0 => coefIn(2),  -- sfix24_En24
              addin => tapout_1,  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_1,  -- sfix24_En24
              tapout => tapout_2  -- sfix52_En48
              );

  u_FilterTap_4 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_1,  -- sfix24_En24
              coefIn_0 => coefIn(3),  -- sfix24_En24
              addin => tapout_2,  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_2,  -- sfix24_En24
              tapout => tapout_3  -- sfix52_En48
              );

  u_FilterTap_5 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_2,  -- sfix24_En24
              coefIn_0 => coefIn(4),  -- sfix24_En24
              addin => tapout_3,  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_3,  -- sfix24_En24
              tapout => tapout_4  -- sfix52_En48
              );

  u_FilterTap_6 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_3,  -- sfix24_En24
              coefIn_0 => coefIn(5),  -- sfix24_En24
              addin => tapout_4,  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_4,  -- sfix24_En24
              tapout => tapout_5  -- sfix52_En48
              );

  u_FilterTap_7 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_4,  -- sfix24_En24
              coefIn_0 => coefIn(6),  -- sfix24_En24
              addin => tapout_5,  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_5,  -- sfix24_En24
              tapout => tapout_6  -- sfix52_En48
              );

  u_FilterTap_8 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_5,  -- sfix24_En24
              coefIn_0 => coefIn(7),  -- sfix24_En24
              addin => tapout_6,  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_6,  -- sfix24_En24
              tapout => tapout_7  -- sfix52_En48
              );

  u_FilterTap_9 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_6,  -- sfix24_En24
              coefIn_0 => coefIn(8),  -- sfix24_En24
              addin => tapout_7,  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_7,  -- sfix24_En24
              tapout => tapout_8  -- sfix52_En48
              );

  u_FilterTap_10 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_7,  -- sfix24_En24
              coefIn_0 => coefIn(9),  -- sfix24_En24
              addin => tapout_8,  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_8,  -- sfix24_En24
              tapout => tapout_9  -- sfix52_En48
              );

  u_FilterTap_11 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_8,  -- sfix24_En24
              coefIn_0 => coefIn(10),  -- sfix24_En24
              addin => tapout_9,  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_9,  -- sfix24_En24
              tapout => tapout_10  -- sfix52_En48
              );

  u_FilterTap_12 : FilterTapSystolicWvldin_12
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_9,  -- sfix24_En24
              coefIn_0 => coefIn(11),  -- sfix24_En24
              addin => tapout_10,  -- sfix52_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_10,  -- sfix24_En24
              tapout => tapout_11  -- sfix52_En48
              );

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          intdelay_reg <= (OTHERS => '0');
        ELSIF dinRegVld = '1' THEN
          intdelay_reg(0) <= dinRegVld;
          intdelay_reg(1 TO 14) <= intdelay_reg(0 TO 13);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;

  vldShift <= intdelay_reg(14);

  vldOutTmp <= dinRegVld AND vldShift;

  ZERO_OUT <= to_signed(16#000000#, 24);

  addin <= to_signed(0, 52);

  tapout_signed <= signed(tapout_11);

  dout_cast <= tapout_signed(47 DOWNTO 24);

  
  muxOut <= ZERO_OUT WHEN vldOutTmp = '0' ELSE
      dout_cast;

  intdelay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dout_1_re_tmp <= to_signed(16#000000#, 24);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dout_1_re_tmp <= to_signed(16#000000#, 24);
        ELSE 
          dout_1_re_tmp <= muxOut;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  dout_1_re <= std_logic_vector(dout_1_re_tmp);

  intdelay_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        doutVld <= '0';
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          doutVld <= '0';
        ELSE 
          doutVld <= vldOutTmp;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


END rtl;

