-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fir_filter2\Discrete_FIR_Filter.vhd
-- Created: 2020-11-18 17:33:05
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Discrete_FIR_Filter
-- Source Path: fir_filter2/FIR Filter Subsystem/Discrete FIR Filter
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.top_level_pkg.ALL;

ENTITY Discrete_FIR_Filter_24 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                                 :   IN    std_logic;
        Discrete_FIR_Filter_in            :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        Discrete_FIR_Filter_coeff         :   IN    vector_of_std_logic_vector24(0 TO 23);  -- sfix24_En24 [24]
        Discrete_FIR_Filter_out           :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En24
        );
END Discrete_FIR_Filter_24;


ARCHITECTURE rtl OF Discrete_FIR_Filter_24 IS

  -- Signals
  SIGNAL Discrete_FIR_Filter_in_signed    : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_0      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL delay_pipeline_1                 : vector_of_signed24(0 TO 22) := (others => (others => '0'));  -- sfix24_En24 [23]
  SIGNAL product1                         : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL delay_pipeline_0                 : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_1      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product2                         : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast                   : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL adder_add_cast_1                 : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum1                             : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_1_1               : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_2      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product3                         : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_2                 : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum2                             : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_2                 : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_3      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product4                         : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_3                 : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum3                             : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_3                 : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_4      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product5                         : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_4                 : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum4                             : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_4                 : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_5      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product6                         : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_5                 : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum5                             : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_5                 : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_6      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product7                         : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_6                 : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum6                             : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_6                 : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_7      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product8                         : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_7                 : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum7                             : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_7                 : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_8      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product9                         : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_8                 : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum8                             : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_8                 : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_9      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product10                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_9                 : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum9                             : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_9                 : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_10     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product11                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_10                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum10                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_10                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_11     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product12                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_11                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum11                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_11                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_12     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product13                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_12                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum12                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_12                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_13     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product14                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_13                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum13                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_13                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_14     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product15                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_14                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum14                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_14                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_15     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product16                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_15                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum15                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_15                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_16     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product17                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_16                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum16                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_16                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_17     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product18                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_17                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum17                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_17                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_18     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product19                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_18                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum18                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_18                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_19     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product20                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_19                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum19                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_19                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_20     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product21                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_20                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum20                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_20                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_21     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product22                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_21                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum21                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_21                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_22     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product23                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_22                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum22                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL delay_pipeline_22                : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL Discrete_FIR_Filter_coeff_23     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL product24                        : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL adder_add_cast_23                : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL sum23                            : signed(52 DOWNTO 0) := (others => '0');  -- sfix53_En48
  SIGNAL output_typeconvert               : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24

BEGIN
  Discrete_FIR_Filter_in_signed <= signed(Discrete_FIR_Filter_in);

  Discrete_FIR_Filter_coeff_0 <= signed(Discrete_FIR_Filter_coeff(0));

  Delay_Pipeline_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delay_pipeline_1 <= (OTHERS => to_signed(16#000000#, 24));
      ELSIF enb = '1' THEN
        delay_pipeline_1(0) <= Discrete_FIR_Filter_in_signed;
        delay_pipeline_1(1 TO 22) <= delay_pipeline_1(0 TO 21);
      END IF;
    END IF;
  END PROCESS Delay_Pipeline_process;


  product1 <= Discrete_FIR_Filter_in_signed * Discrete_FIR_Filter_coeff_0;

  delay_pipeline_0 <= delay_pipeline_1(0);

  Discrete_FIR_Filter_coeff_1 <= signed(Discrete_FIR_Filter_coeff(1));

  product2 <= delay_pipeline_0 * Discrete_FIR_Filter_coeff_1;

  adder_add_cast <= resize(product1, 53);
  adder_add_cast_1 <= resize(product2, 53);
  sum1 <= adder_add_cast + adder_add_cast_1;

  delay_pipeline_1_1 <= delay_pipeline_1(1);

  Discrete_FIR_Filter_coeff_2 <= signed(Discrete_FIR_Filter_coeff(2));

  product3 <= delay_pipeline_1_1 * Discrete_FIR_Filter_coeff_2;

  adder_add_cast_2 <= resize(product3, 53);
  sum2 <= sum1 + adder_add_cast_2;

  delay_pipeline_2 <= delay_pipeline_1(2);

  Discrete_FIR_Filter_coeff_3 <= signed(Discrete_FIR_Filter_coeff(3));

  product4 <= delay_pipeline_2 * Discrete_FIR_Filter_coeff_3;

  adder_add_cast_3 <= resize(product4, 53);
  sum3 <= sum2 + adder_add_cast_3;

  delay_pipeline_3 <= delay_pipeline_1(3);

  Discrete_FIR_Filter_coeff_4 <= signed(Discrete_FIR_Filter_coeff(4));

  product5 <= delay_pipeline_3 * Discrete_FIR_Filter_coeff_4;

  adder_add_cast_4 <= resize(product5, 53);
  sum4 <= sum3 + adder_add_cast_4;

  delay_pipeline_4 <= delay_pipeline_1(4);

  Discrete_FIR_Filter_coeff_5 <= signed(Discrete_FIR_Filter_coeff(5));

  product6 <= delay_pipeline_4 * Discrete_FIR_Filter_coeff_5;

  adder_add_cast_5 <= resize(product6, 53);
  sum5 <= sum4 + adder_add_cast_5;

  delay_pipeline_5 <= delay_pipeline_1(5);

  Discrete_FIR_Filter_coeff_6 <= signed(Discrete_FIR_Filter_coeff(6));

  product7 <= delay_pipeline_5 * Discrete_FIR_Filter_coeff_6;

  adder_add_cast_6 <= resize(product7, 53);
  sum6 <= sum5 + adder_add_cast_6;

  delay_pipeline_6 <= delay_pipeline_1(6);

  Discrete_FIR_Filter_coeff_7 <= signed(Discrete_FIR_Filter_coeff(7));

  product8 <= delay_pipeline_6 * Discrete_FIR_Filter_coeff_7;

  adder_add_cast_7 <= resize(product8, 53);
  sum7 <= sum6 + adder_add_cast_7;

  delay_pipeline_7 <= delay_pipeline_1(7);

  Discrete_FIR_Filter_coeff_8 <= signed(Discrete_FIR_Filter_coeff(8));

  product9 <= delay_pipeline_7 * Discrete_FIR_Filter_coeff_8;

  adder_add_cast_8 <= resize(product9, 53);
  sum8 <= sum7 + adder_add_cast_8;

  delay_pipeline_8 <= delay_pipeline_1(8);

  Discrete_FIR_Filter_coeff_9 <= signed(Discrete_FIR_Filter_coeff(9));

  product10 <= delay_pipeline_8 * Discrete_FIR_Filter_coeff_9;

  adder_add_cast_9 <= resize(product10, 53);
  sum9 <= sum8 + adder_add_cast_9;

  delay_pipeline_9 <= delay_pipeline_1(9);

  Discrete_FIR_Filter_coeff_10 <= signed(Discrete_FIR_Filter_coeff(10));

  product11 <= delay_pipeline_9 * Discrete_FIR_Filter_coeff_10;

  adder_add_cast_10 <= resize(product11, 53);
  sum10 <= sum9 + adder_add_cast_10;

  delay_pipeline_10 <= delay_pipeline_1(10);

  Discrete_FIR_Filter_coeff_11 <= signed(Discrete_FIR_Filter_coeff(11));

  product12 <= delay_pipeline_10 * Discrete_FIR_Filter_coeff_11;

  adder_add_cast_11 <= resize(product12, 53);
  sum11 <= sum10 + adder_add_cast_11;

  delay_pipeline_11 <= delay_pipeline_1(11);

  Discrete_FIR_Filter_coeff_12 <= signed(Discrete_FIR_Filter_coeff(12));

  product13 <= delay_pipeline_11 * Discrete_FIR_Filter_coeff_12;

  adder_add_cast_12 <= resize(product13, 53);
  sum12 <= sum11 + adder_add_cast_12;

  delay_pipeline_12 <= delay_pipeline_1(12);

  Discrete_FIR_Filter_coeff_13 <= signed(Discrete_FIR_Filter_coeff(13));

  product14 <= delay_pipeline_12 * Discrete_FIR_Filter_coeff_13;

  adder_add_cast_13 <= resize(product14, 53);
  sum13 <= sum12 + adder_add_cast_13;

  delay_pipeline_13 <= delay_pipeline_1(13);

  Discrete_FIR_Filter_coeff_14 <= signed(Discrete_FIR_Filter_coeff(14));

  product15 <= delay_pipeline_13 * Discrete_FIR_Filter_coeff_14;

  adder_add_cast_14 <= resize(product15, 53);
  sum14 <= sum13 + adder_add_cast_14;

  delay_pipeline_14 <= delay_pipeline_1(14);

  Discrete_FIR_Filter_coeff_15 <= signed(Discrete_FIR_Filter_coeff(15));

  product16 <= delay_pipeline_14 * Discrete_FIR_Filter_coeff_15;

  adder_add_cast_15 <= resize(product16, 53);
  sum15 <= sum14 + adder_add_cast_15;

  delay_pipeline_15 <= delay_pipeline_1(15);

  Discrete_FIR_Filter_coeff_16 <= signed(Discrete_FIR_Filter_coeff(16));

  product17 <= delay_pipeline_15 * Discrete_FIR_Filter_coeff_16;

  adder_add_cast_16 <= resize(product17, 53);
  sum16 <= sum15 + adder_add_cast_16;

  delay_pipeline_16 <= delay_pipeline_1(16);

  Discrete_FIR_Filter_coeff_17 <= signed(Discrete_FIR_Filter_coeff(17));

  product18 <= delay_pipeline_16 * Discrete_FIR_Filter_coeff_17;

  adder_add_cast_17 <= resize(product18, 53);
  sum17 <= sum16 + adder_add_cast_17;

  delay_pipeline_17 <= delay_pipeline_1(17);

  Discrete_FIR_Filter_coeff_18 <= signed(Discrete_FIR_Filter_coeff(18));

  product19 <= delay_pipeline_17 * Discrete_FIR_Filter_coeff_18;

  adder_add_cast_18 <= resize(product19, 53);
  sum18 <= sum17 + adder_add_cast_18;

  delay_pipeline_18 <= delay_pipeline_1(18);

  Discrete_FIR_Filter_coeff_19 <= signed(Discrete_FIR_Filter_coeff(19));

  product20 <= delay_pipeline_18 * Discrete_FIR_Filter_coeff_19;

  adder_add_cast_19 <= resize(product20, 53);
  sum19 <= sum18 + adder_add_cast_19;

  delay_pipeline_19 <= delay_pipeline_1(19);

  Discrete_FIR_Filter_coeff_20 <= signed(Discrete_FIR_Filter_coeff(20));

  product21 <= delay_pipeline_19 * Discrete_FIR_Filter_coeff_20;

  adder_add_cast_20 <= resize(product21, 53);
  sum20 <= sum19 + adder_add_cast_20;

  delay_pipeline_20 <= delay_pipeline_1(20);

  Discrete_FIR_Filter_coeff_21 <= signed(Discrete_FIR_Filter_coeff(21));

  product22 <= delay_pipeline_20 * Discrete_FIR_Filter_coeff_21;

  adder_add_cast_21 <= resize(product22, 53);
  sum21 <= sum20 + adder_add_cast_21;

  delay_pipeline_21 <= delay_pipeline_1(21);

  Discrete_FIR_Filter_coeff_22 <= signed(Discrete_FIR_Filter_coeff(22));

  product23 <= delay_pipeline_21 * Discrete_FIR_Filter_coeff_22;

  adder_add_cast_22 <= resize(product23, 53);
  sum22 <= sum21 + adder_add_cast_22;

  delay_pipeline_22 <= delay_pipeline_1(22);

  Discrete_FIR_Filter_coeff_23 <= signed(Discrete_FIR_Filter_coeff(23));

  product24 <= delay_pipeline_22 * Discrete_FIR_Filter_coeff_23;

  adder_add_cast_23 <= resize(product24, 53);
  sum23 <= sum22 + adder_add_cast_23;

  output_typeconvert <= sum23(47 DOWNTO 24);

  Discrete_FIR_Filter_out <= std_logic_vector(output_typeconvert);

END rtl;

