-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\nlms_filter\Subsystem.vhd
-- Created: 2020-11-18 18:01:32
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- output                        ce_out        0.2
-- error_rsvd                    ce_out        0.2
-- weights                       ce_out        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: nlms_filter/Subsystem
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.anc_package.ALL;

ENTITY LMS_Filter_24 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        input                             :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        desired                           :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        adapt                             :   IN    std_logic;
--        ce_out                            :   OUT   std_logic;
--        output                            :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
--        error_rsvd                        :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        weights                           :   OUT   vector_of_std_logic_vector24(0 TO 23)  -- sfix24_En24 [24]
        );
END LMS_Filter_24;


ARCHITECTURE rtl OF LMS_Filter_24 IS

  -- Constants
  CONSTANT C_LMS_FILTER_STEP_SIZE         : signed(23 DOWNTO 0) := 
    "001000000000000000000000";  -- sfix24_En24

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL input_signed                     : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL desired_signed                   : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL LMS_Filter_out1                  : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL LMS_Filter_out2                  : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL LMS_Filter_out3                  : vector_of_signed24(0 TO 23) := (others => (others => '0'));  -- sfix24_En24 [24]
  SIGNAL weight                           : vector_of_signed24(0 TO 23) := (others => (others => '0'));  -- sfix24_En24 [24]
  SIGNAL filter_sum                       : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL data_pipeline                    : vector_of_signed24(0 TO 23) := (others => (others => '0'));  -- sfix24_En24 [24]
  SIGNAL data_pipeline_tmp                : vector_of_signed24(0 TO 22) := (others => (others => '0'));  -- sfix24_En24 [23]
  SIGNAL filter_products                  : vector_of_signed24(0 TO 23) := (others => (others => '0'));  -- sfix24_En24 [24]
  SIGNAL mul_temp                         : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_1                       : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_2                       : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_3                       : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_4                       : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_5                       : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_6                       : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_7                       : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_8                       : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_9                       : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_10                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_11                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_12                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_13                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_14                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_15                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_16                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_17                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_18                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_19                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_20                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_21                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_22                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_23                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL sum_1                            : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast                         : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_1                       : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp                         : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_2                            : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_2                       : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_3                       : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_1                       : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_3                            : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_4                       : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_5                       : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_2                       : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_4                            : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_6                       : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_7                       : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_3                       : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_5                            : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_8                       : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_9                       : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_4                       : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_6                            : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_10                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_11                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_5                       : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_7                            : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_12                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_13                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_6                       : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_8                            : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_14                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_15                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_7                       : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_9                            : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_16                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_17                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_8                       : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_10                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_18                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_19                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_9                       : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_11                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_20                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_21                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_10                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_12                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_22                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_23                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_11                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_13                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_24                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_25                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_12                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_14                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_26                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_27                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_13                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_15                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_28                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_29                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_14                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_16                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_30                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_31                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_15                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_17                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_32                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_33                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_16                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_18                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_34                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_35                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_17                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_19                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_36                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_37                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_18                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_20                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_38                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_39                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_19                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_21                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_40                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_41                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_20                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sum_22                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_42                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_43                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_21                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_44                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_45                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_22                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL sub_cast                         : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL sub_cast_1                       : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL sub_temp                         : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL mu_err                           : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL mul_temp_24                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mu_err_data_prod                 : vector_of_signed24(0 TO 23) := (others => (others => '0'));  -- sfix24_En24 [24]
  SIGNAL mul_temp_25                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_26                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_27                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_28                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_29                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_30                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_31                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_32                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_33                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_34                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_35                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_36                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_37                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_38                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_39                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_40                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_41                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_42                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_43                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_44                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_45                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_46                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_47                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL mul_temp_48                      : signed(47 DOWNTO 0) := (others => '0');  -- sfix48_En48
  SIGNAL weight_adder_output              : vector_of_signed24(0 TO 23) := (others => (others => '0'));  -- sfix24_En24 [24]
  SIGNAL add_cast_46                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_47                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_23                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_48                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_49                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_24                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_50                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_51                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_25                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_52                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_53                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_26                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_54                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_55                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_27                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_56                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_57                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_28                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_58                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_59                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_29                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_60                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_61                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_30                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_62                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_63                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_31                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_64                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_65                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_32                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_66                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_67                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_33                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_68                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_69                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_34                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_70                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_71                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_35                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_72                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_73                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_36                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_74                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_75                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_37                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_76                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_77                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_38                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_78                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_79                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_39                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_80                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_81                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_40                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_82                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_83                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_41                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_84                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_85                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_42                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_86                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_87                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_43                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_88                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_89                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_44                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_90                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_91                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_45                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL add_cast_92                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_cast_93                      : signed(23 DOWNTO 0) := (others => '0');  -- sfix24_En24
  SIGNAL add_temp_46                      : signed(24 DOWNTO 0) := (others => '0');  -- sfix25_En24
  SIGNAL weight_backwards                 : vector_of_signed24(0 TO 23) := (others => (others => '0'));  -- sfix24_En24 [24]

BEGIN
  input_signed <= signed(input);

  desired_signed <= signed(desired);

  enb <= clk_enable;


-- ***********************
-- ********* LMS *********
-- ***********************

-- * LMS: FIR section

  LMS_Filter_24_del_temp_process1 : PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        data_pipeline_tmp <= (OTHERS => (OTHERS => '0'));
      ELSIF enb = '1' THEN
        data_pipeline_tmp(0 TO 21) <= data_pipeline_tmp(1 TO 22);
        data_pipeline_tmp(22) <= input_signed;
      END IF;
    END IF;
  END PROCESS LMS_Filter_24_del_temp_process1;

  data_pipeline(0 TO 22) <= data_pipeline_tmp(0 TO 22);
  data_pipeline(23) <= input_signed;

  mul_temp <= data_pipeline(0) * weight(0);
  filter_products(0) <= mul_temp(47 DOWNTO 24);

  mul_temp_1 <= data_pipeline(1) * weight(1);
  filter_products(1) <= mul_temp_1(47 DOWNTO 24);

  mul_temp_2 <= data_pipeline(2) * weight(2);
  filter_products(2) <= mul_temp_2(47 DOWNTO 24);

  mul_temp_3 <= data_pipeline(3) * weight(3);
  filter_products(3) <= mul_temp_3(47 DOWNTO 24);

  mul_temp_4 <= data_pipeline(4) * weight(4);
  filter_products(4) <= mul_temp_4(47 DOWNTO 24);

  mul_temp_5 <= data_pipeline(5) * weight(5);
  filter_products(5) <= mul_temp_5(47 DOWNTO 24);

  mul_temp_6 <= data_pipeline(6) * weight(6);
  filter_products(6) <= mul_temp_6(47 DOWNTO 24);

  mul_temp_7 <= data_pipeline(7) * weight(7);
  filter_products(7) <= mul_temp_7(47 DOWNTO 24);

  mul_temp_8 <= data_pipeline(8) * weight(8);
  filter_products(8) <= mul_temp_8(47 DOWNTO 24);

  mul_temp_9 <= data_pipeline(9) * weight(9);
  filter_products(9) <= mul_temp_9(47 DOWNTO 24);

  mul_temp_10 <= data_pipeline(10) * weight(10);
  filter_products(10) <= mul_temp_10(47 DOWNTO 24);

  mul_temp_11 <= data_pipeline(11) * weight(11);
  filter_products(11) <= mul_temp_11(47 DOWNTO 24);

  mul_temp_12 <= data_pipeline(12) * weight(12);
  filter_products(12) <= mul_temp_12(47 DOWNTO 24);

  mul_temp_13 <= data_pipeline(13) * weight(13);
  filter_products(13) <= mul_temp_13(47 DOWNTO 24);

  mul_temp_14 <= data_pipeline(14) * weight(14);
  filter_products(14) <= mul_temp_14(47 DOWNTO 24);

  mul_temp_15 <= data_pipeline(15) * weight(15);
  filter_products(15) <= mul_temp_15(47 DOWNTO 24);

  mul_temp_16 <= data_pipeline(16) * weight(16);
  filter_products(16) <= mul_temp_16(47 DOWNTO 24);

  mul_temp_17 <= data_pipeline(17) * weight(17);
  filter_products(17) <= mul_temp_17(47 DOWNTO 24);

  mul_temp_18 <= data_pipeline(18) * weight(18);
  filter_products(18) <= mul_temp_18(47 DOWNTO 24);

  mul_temp_19 <= data_pipeline(19) * weight(19);
  filter_products(19) <= mul_temp_19(47 DOWNTO 24);

  mul_temp_20 <= data_pipeline(20) * weight(20);
  filter_products(20) <= mul_temp_20(47 DOWNTO 24);

  mul_temp_21 <= data_pipeline(21) * weight(21);
  filter_products(21) <= mul_temp_21(47 DOWNTO 24);

  mul_temp_22 <= data_pipeline(22) * weight(22);
  filter_products(22) <= mul_temp_22(47 DOWNTO 24);

  mul_temp_23 <= data_pipeline(23) * weight(23);
  filter_products(23) <= mul_temp_23(47 DOWNTO 24);

-- linear sum of filter products

  add_cast <= filter_products(0);
  add_cast_1 <= filter_products(1);
  add_temp <= resize(add_cast, 25) + resize(add_cast_1, 25);
  sum_1 <= add_temp(23 DOWNTO 0);

  add_cast_2 <= sum_1;
  add_cast_3 <= filter_products(2);
  add_temp_1 <= resize(add_cast_2, 25) + resize(add_cast_3, 25);
  sum_2 <= add_temp_1(23 DOWNTO 0);

  add_cast_4 <= sum_2;
  add_cast_5 <= filter_products(3);
  add_temp_2 <= resize(add_cast_4, 25) + resize(add_cast_5, 25);
  sum_3 <= add_temp_2(23 DOWNTO 0);

  add_cast_6 <= sum_3;
  add_cast_7 <= filter_products(4);
  add_temp_3 <= resize(add_cast_6, 25) + resize(add_cast_7, 25);
  sum_4 <= add_temp_3(23 DOWNTO 0);

  add_cast_8 <= sum_4;
  add_cast_9 <= filter_products(5);
  add_temp_4 <= resize(add_cast_8, 25) + resize(add_cast_9, 25);
  sum_5 <= add_temp_4(23 DOWNTO 0);

  add_cast_10 <= sum_5;
  add_cast_11 <= filter_products(6);
  add_temp_5 <= resize(add_cast_10, 25) + resize(add_cast_11, 25);
  sum_6 <= add_temp_5(23 DOWNTO 0);

  add_cast_12 <= sum_6;
  add_cast_13 <= filter_products(7);
  add_temp_6 <= resize(add_cast_12, 25) + resize(add_cast_13, 25);
  sum_7 <= add_temp_6(23 DOWNTO 0);

  add_cast_14 <= sum_7;
  add_cast_15 <= filter_products(8);
  add_temp_7 <= resize(add_cast_14, 25) + resize(add_cast_15, 25);
  sum_8 <= add_temp_7(23 DOWNTO 0);

  add_cast_16 <= sum_8;
  add_cast_17 <= filter_products(9);
  add_temp_8 <= resize(add_cast_16, 25) + resize(add_cast_17, 25);
  sum_9 <= add_temp_8(23 DOWNTO 0);

  add_cast_18 <= sum_9;
  add_cast_19 <= filter_products(10);
  add_temp_9 <= resize(add_cast_18, 25) + resize(add_cast_19, 25);
  sum_10 <= add_temp_9(23 DOWNTO 0);

  add_cast_20 <= sum_10;
  add_cast_21 <= filter_products(11);
  add_temp_10 <= resize(add_cast_20, 25) + resize(add_cast_21, 25);
  sum_11 <= add_temp_10(23 DOWNTO 0);

  add_cast_22 <= sum_11;
  add_cast_23 <= filter_products(12);
  add_temp_11 <= resize(add_cast_22, 25) + resize(add_cast_23, 25);
  sum_12 <= add_temp_11(23 DOWNTO 0);

  add_cast_24 <= sum_12;
  add_cast_25 <= filter_products(13);
  add_temp_12 <= resize(add_cast_24, 25) + resize(add_cast_25, 25);
  sum_13 <= add_temp_12(23 DOWNTO 0);

  add_cast_26 <= sum_13;
  add_cast_27 <= filter_products(14);
  add_temp_13 <= resize(add_cast_26, 25) + resize(add_cast_27, 25);
  sum_14 <= add_temp_13(23 DOWNTO 0);

  add_cast_28 <= sum_14;
  add_cast_29 <= filter_products(15);
  add_temp_14 <= resize(add_cast_28, 25) + resize(add_cast_29, 25);
  sum_15 <= add_temp_14(23 DOWNTO 0);

  add_cast_30 <= sum_15;
  add_cast_31 <= filter_products(16);
  add_temp_15 <= resize(add_cast_30, 25) + resize(add_cast_31, 25);
  sum_16 <= add_temp_15(23 DOWNTO 0);

  add_cast_32 <= sum_16;
  add_cast_33 <= filter_products(17);
  add_temp_16 <= resize(add_cast_32, 25) + resize(add_cast_33, 25);
  sum_17 <= add_temp_16(23 DOWNTO 0);

  add_cast_34 <= sum_17;
  add_cast_35 <= filter_products(18);
  add_temp_17 <= resize(add_cast_34, 25) + resize(add_cast_35, 25);
  sum_18 <= add_temp_17(23 DOWNTO 0);

  add_cast_36 <= sum_18;
  add_cast_37 <= filter_products(19);
  add_temp_18 <= resize(add_cast_36, 25) + resize(add_cast_37, 25);
  sum_19 <= add_temp_18(23 DOWNTO 0);

  add_cast_38 <= sum_19;
  add_cast_39 <= filter_products(20);
  add_temp_19 <= resize(add_cast_38, 25) + resize(add_cast_39, 25);
  sum_20 <= add_temp_19(23 DOWNTO 0);

  add_cast_40 <= sum_20;
  add_cast_41 <= filter_products(21);
  add_temp_20 <= resize(add_cast_40, 25) + resize(add_cast_41, 25);
  sum_21 <= add_temp_20(23 DOWNTO 0);

  add_cast_42 <= sum_21;
  add_cast_43 <= filter_products(22);
  add_temp_21 <= resize(add_cast_42, 25) + resize(add_cast_43, 25);
  sum_22 <= add_temp_21(23 DOWNTO 0);

  add_cast_44 <= sum_22;
  add_cast_45 <= filter_products(23);
  add_temp_22 <= resize(add_cast_44, 25) + resize(add_cast_45, 25);
  filter_sum <= add_temp_22(23 DOWNTO 0);

  LMS_Filter_out1 <= filter_sum;

-- * Calculate Filter Error

  sub_cast <= desired_signed;
  sub_cast_1 <= filter_sum;
  sub_temp <= resize(sub_cast, 25) - resize(sub_cast_1, 25);
  LMS_Filter_out2 <= sub_temp(23 DOWNTO 0);

-- ***** LMS Weight Update Function *****

  mul_temp_24 <= C_LMS_FILTER_STEP_SIZE * LMS_Filter_out2;
  mu_err <= mul_temp_24(47 DOWNTO 24);

  mul_temp_25 <= data_pipeline(0) * mu_err;
  mu_err_data_prod(0) <= mul_temp_25(47 DOWNTO 24);

  mul_temp_26 <= data_pipeline(1) * mu_err;
  mu_err_data_prod(1) <= mul_temp_26(47 DOWNTO 24);

  mul_temp_27 <= data_pipeline(2) * mu_err;
  mu_err_data_prod(2) <= mul_temp_27(47 DOWNTO 24);

  mul_temp_28 <= data_pipeline(3) * mu_err;
  mu_err_data_prod(3) <= mul_temp_28(47 DOWNTO 24);

  mul_temp_29 <= data_pipeline(4) * mu_err;
  mu_err_data_prod(4) <= mul_temp_29(47 DOWNTO 24);

  mul_temp_30 <= data_pipeline(5) * mu_err;
  mu_err_data_prod(5) <= mul_temp_30(47 DOWNTO 24);

  mul_temp_31 <= data_pipeline(6) * mu_err;
  mu_err_data_prod(6) <= mul_temp_31(47 DOWNTO 24);

  mul_temp_32 <= data_pipeline(7) * mu_err;
  mu_err_data_prod(7) <= mul_temp_32(47 DOWNTO 24);

  mul_temp_33 <= data_pipeline(8) * mu_err;
  mu_err_data_prod(8) <= mul_temp_33(47 DOWNTO 24);

  mul_temp_34 <= data_pipeline(9) * mu_err;
  mu_err_data_prod(9) <= mul_temp_34(47 DOWNTO 24);

  mul_temp_35 <= data_pipeline(10) * mu_err;
  mu_err_data_prod(10) <= mul_temp_35(47 DOWNTO 24);

  mul_temp_36 <= data_pipeline(11) * mu_err;
  mu_err_data_prod(11) <= mul_temp_36(47 DOWNTO 24);

  mul_temp_37 <= data_pipeline(12) * mu_err;
  mu_err_data_prod(12) <= mul_temp_37(47 DOWNTO 24);

  mul_temp_38 <= data_pipeline(13) * mu_err;
  mu_err_data_prod(13) <= mul_temp_38(47 DOWNTO 24);

  mul_temp_39 <= data_pipeline(14) * mu_err;
  mu_err_data_prod(14) <= mul_temp_39(47 DOWNTO 24);

  mul_temp_40 <= data_pipeline(15) * mu_err;
  mu_err_data_prod(15) <= mul_temp_40(47 DOWNTO 24);

  mul_temp_41 <= data_pipeline(16) * mu_err;
  mu_err_data_prod(16) <= mul_temp_41(47 DOWNTO 24);

  mul_temp_42 <= data_pipeline(17) * mu_err;
  mu_err_data_prod(17) <= mul_temp_42(47 DOWNTO 24);

  mul_temp_43 <= data_pipeline(18) * mu_err;
  mu_err_data_prod(18) <= mul_temp_43(47 DOWNTO 24);

  mul_temp_44 <= data_pipeline(19) * mu_err;
  mu_err_data_prod(19) <= mul_temp_44(47 DOWNTO 24);

  mul_temp_45 <= data_pipeline(20) * mu_err;
  mu_err_data_prod(20) <= mul_temp_45(47 DOWNTO 24);

  mul_temp_46 <= data_pipeline(21) * mu_err;
  mu_err_data_prod(21) <= mul_temp_46(47 DOWNTO 24);

  mul_temp_47 <= data_pipeline(22) * mu_err;
  mu_err_data_prod(22) <= mul_temp_47(47 DOWNTO 24);

  mul_temp_48 <= data_pipeline(23) * mu_err;
  mu_err_data_prod(23) <= mul_temp_48(47 DOWNTO 24);

-- * LMS_Filter Weight Accumulator

  add_cast_46 <= weight(0);
  add_cast_47 <= mu_err_data_prod(0);
  add_temp_23 <= resize(add_cast_46, 25) + resize(add_cast_47, 25);
  weight_adder_output(0) <= add_temp_23(23 DOWNTO 0);

  add_cast_48 <= weight(1);
  add_cast_49 <= mu_err_data_prod(1);
  add_temp_24 <= resize(add_cast_48, 25) + resize(add_cast_49, 25);
  weight_adder_output(1) <= add_temp_24(23 DOWNTO 0);

  add_cast_50 <= weight(2);
  add_cast_51 <= mu_err_data_prod(2);
  add_temp_25 <= resize(add_cast_50, 25) + resize(add_cast_51, 25);
  weight_adder_output(2) <= add_temp_25(23 DOWNTO 0);

  add_cast_52 <= weight(3);
  add_cast_53 <= mu_err_data_prod(3);
  add_temp_26 <= resize(add_cast_52, 25) + resize(add_cast_53, 25);
  weight_adder_output(3) <= add_temp_26(23 DOWNTO 0);

  add_cast_54 <= weight(4);
  add_cast_55 <= mu_err_data_prod(4);
  add_temp_27 <= resize(add_cast_54, 25) + resize(add_cast_55, 25);
  weight_adder_output(4) <= add_temp_27(23 DOWNTO 0);

  add_cast_56 <= weight(5);
  add_cast_57 <= mu_err_data_prod(5);
  add_temp_28 <= resize(add_cast_56, 25) + resize(add_cast_57, 25);
  weight_adder_output(5) <= add_temp_28(23 DOWNTO 0);

  add_cast_58 <= weight(6);
  add_cast_59 <= mu_err_data_prod(6);
  add_temp_29 <= resize(add_cast_58, 25) + resize(add_cast_59, 25);
  weight_adder_output(6) <= add_temp_29(23 DOWNTO 0);

  add_cast_60 <= weight(7);
  add_cast_61 <= mu_err_data_prod(7);
  add_temp_30 <= resize(add_cast_60, 25) + resize(add_cast_61, 25);
  weight_adder_output(7) <= add_temp_30(23 DOWNTO 0);

  add_cast_62 <= weight(8);
  add_cast_63 <= mu_err_data_prod(8);
  add_temp_31 <= resize(add_cast_62, 25) + resize(add_cast_63, 25);
  weight_adder_output(8) <= add_temp_31(23 DOWNTO 0);

  add_cast_64 <= weight(9);
  add_cast_65 <= mu_err_data_prod(9);
  add_temp_32 <= resize(add_cast_64, 25) + resize(add_cast_65, 25);
  weight_adder_output(9) <= add_temp_32(23 DOWNTO 0);

  add_cast_66 <= weight(10);
  add_cast_67 <= mu_err_data_prod(10);
  add_temp_33 <= resize(add_cast_66, 25) + resize(add_cast_67, 25);
  weight_adder_output(10) <= add_temp_33(23 DOWNTO 0);

  add_cast_68 <= weight(11);
  add_cast_69 <= mu_err_data_prod(11);
  add_temp_34 <= resize(add_cast_68, 25) + resize(add_cast_69, 25);
  weight_adder_output(11) <= add_temp_34(23 DOWNTO 0);

  add_cast_70 <= weight(12);
  add_cast_71 <= mu_err_data_prod(12);
  add_temp_35 <= resize(add_cast_70, 25) + resize(add_cast_71, 25);
  weight_adder_output(12) <= add_temp_35(23 DOWNTO 0);

  add_cast_72 <= weight(13);
  add_cast_73 <= mu_err_data_prod(13);
  add_temp_36 <= resize(add_cast_72, 25) + resize(add_cast_73, 25);
  weight_adder_output(13) <= add_temp_36(23 DOWNTO 0);

  add_cast_74 <= weight(14);
  add_cast_75 <= mu_err_data_prod(14);
  add_temp_37 <= resize(add_cast_74, 25) + resize(add_cast_75, 25);
  weight_adder_output(14) <= add_temp_37(23 DOWNTO 0);

  add_cast_76 <= weight(15);
  add_cast_77 <= mu_err_data_prod(15);
  add_temp_38 <= resize(add_cast_76, 25) + resize(add_cast_77, 25);
  weight_adder_output(15) <= add_temp_38(23 DOWNTO 0);

  add_cast_78 <= weight(16);
  add_cast_79 <= mu_err_data_prod(16);
  add_temp_39 <= resize(add_cast_78, 25) + resize(add_cast_79, 25);
  weight_adder_output(16) <= add_temp_39(23 DOWNTO 0);

  add_cast_80 <= weight(17);
  add_cast_81 <= mu_err_data_prod(17);
  add_temp_40 <= resize(add_cast_80, 25) + resize(add_cast_81, 25);
  weight_adder_output(17) <= add_temp_40(23 DOWNTO 0);

  add_cast_82 <= weight(18);
  add_cast_83 <= mu_err_data_prod(18);
  add_temp_41 <= resize(add_cast_82, 25) + resize(add_cast_83, 25);
  weight_adder_output(18) <= add_temp_41(23 DOWNTO 0);

  add_cast_84 <= weight(19);
  add_cast_85 <= mu_err_data_prod(19);
  add_temp_42 <= resize(add_cast_84, 25) + resize(add_cast_85, 25);
  weight_adder_output(19) <= add_temp_42(23 DOWNTO 0);

  add_cast_86 <= weight(20);
  add_cast_87 <= mu_err_data_prod(20);
  add_temp_43 <= resize(add_cast_86, 25) + resize(add_cast_87, 25);
  weight_adder_output(20) <= add_temp_43(23 DOWNTO 0);

  add_cast_88 <= weight(21);
  add_cast_89 <= mu_err_data_prod(21);
  add_temp_44 <= resize(add_cast_88, 25) + resize(add_cast_89, 25);
  weight_adder_output(21) <= add_temp_44(23 DOWNTO 0);

  add_cast_90 <= weight(22);
  add_cast_91 <= mu_err_data_prod(22);
  add_temp_45 <= resize(add_cast_90, 25) + resize(add_cast_91, 25);
  weight_adder_output(22) <= add_temp_45(23 DOWNTO 0);

  add_cast_92 <= weight(23);
  add_cast_93 <= mu_err_data_prod(23);
  add_temp_46 <= resize(add_cast_92, 25) + resize(add_cast_93, 25);
  weight_adder_output(23) <= add_temp_46(23 DOWNTO 0);

    LMS_Filter_24_acc_temp_process2 : PROCESS (clk)
    BEGIN
        IF clk'event AND clk = '1' THEN
            IF reset = '1' THEN
                weight <= (OTHERS => (OTHERS => '0'));
            ELSIF enb = '1' AND adapt = '1' THEN
                weight(0 TO 23) <= weight_adder_output(0 TO 23);
            END IF;
        END IF;
    END PROCESS LMS_Filter_24_acc_temp_process2;

-- * LMS_Filter Weight Output Port

  weight_backwards <= weight_adder_output WHEN ( adapt = '1' ) ELSE
                      weight;
  LMS_Filter_out3(23) <= weight_backwards(0);
  LMS_Filter_out3(22) <= weight_backwards(1);
  LMS_Filter_out3(21) <= weight_backwards(2);
  LMS_Filter_out3(20) <= weight_backwards(3);
  LMS_Filter_out3(19) <= weight_backwards(4);
  LMS_Filter_out3(18) <= weight_backwards(5);
  LMS_Filter_out3(17) <= weight_backwards(6);
  LMS_Filter_out3(16) <= weight_backwards(7);
  LMS_Filter_out3(15) <= weight_backwards(8);
  LMS_Filter_out3(14) <= weight_backwards(9);
  LMS_Filter_out3(13) <= weight_backwards(10);
  LMS_Filter_out3(12) <= weight_backwards(11);
  LMS_Filter_out3(11) <= weight_backwards(12);
  LMS_Filter_out3(10) <= weight_backwards(13);
  LMS_Filter_out3(9) <= weight_backwards(14);
  LMS_Filter_out3(8) <= weight_backwards(15);
  LMS_Filter_out3(7) <= weight_backwards(16);
  LMS_Filter_out3(6) <= weight_backwards(17);
  LMS_Filter_out3(5) <= weight_backwards(18);
  LMS_Filter_out3(4) <= weight_backwards(19);
  LMS_Filter_out3(3) <= weight_backwards(20);
  LMS_Filter_out3(2) <= weight_backwards(21);
  LMS_Filter_out3(1) <= weight_backwards(22);
  LMS_Filter_out3(0) <= weight_backwards(23);

  outputgen: FOR k IN 0 TO 23 GENERATE
    weights(k) <= std_logic_vector(LMS_Filter_out3(k));
  END GENERATE;

END rtl;

