-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fir_filter_hdl_optimized_24\Discrete_FIR_Filter_HDL_Optimized_24.vhd
-- Created: 2020-11-19 02:06:49
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Discrete_FIR_Filter_HDL_Optimized_24
-- Source Path: fir_filter_hdl_optimized_24/Subsystem_24/Discrete FIR Filter HDL Optimized 24
-- Hierarchy Level: 1
-- 
-- Discrete FIR Filter HDL Optimized
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.top_level_pkg.ALL;

ENTITY Discrete_FIR_Filter_HDL_Optimized_24 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        validIn                           :   IN    std_logic;
        Coeff                             :   IN    vector_of_std_logic_vector24(0 TO 23);  -- sfix24_En24 [24]
        syncReset                         :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        validOut                          :   OUT   std_logic
        );
END Discrete_FIR_Filter_HDL_Optimized_24;


ARCHITECTURE rtl OF Discrete_FIR_Filter_HDL_Optimized_24 IS

  -- Component Declarations
  COMPONENT FilterBank_24
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
          validIn                         :   IN    std_logic;
          Coeff                           :   IN    vector_of_std_logic_vector24(0 TO 23);  -- sfix24_En24 [24]
          syncReset                       :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterBank_24
    USE ENTITY work.FilterBank_24(rtl);

  -- Signals
  SIGNAL dataOut_tmp                      : std_logic_vector(23 DOWNTO 0);  -- ufix24

BEGIN
  u_FilterBank_24 : FilterBank_24
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => dataIn,  -- sfix24_En24
              validIn => validIn,
              Coeff => Coeff,  -- sfix24_En24 [24]
              syncReset => syncReset,
              dataOut => dataOut_tmp,  -- sfix24_En24
              validOut => validOut
              );

  dataOut <= dataOut_tmp;

END rtl;

