-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\fir_filter_hdl_optimized_24\subFilter_24.vhd
-- Created: 2020-11-19 02:06:49
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: subFilter_24
-- Source Path: fir_filter_hdl_optimized_24/Subsystem_24/Discrete FIR Filter HDL Optimized 24/FilterBank/subFilter_24
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.top_level_pkg.ALL;

ENTITY subFilter_24 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        coefIn                            :   IN    vector_of_std_logic_vector24(0 TO 23);  -- sfix24_En24 [24]
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dout_1_re                         :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
        doutVld                           :   OUT   std_logic
        );
END subFilter_24;


ARCHITECTURE rtl OF subFilter_24 IS

  -- Component Declarations
  COMPONENT FilterTapSystolicWvldin_24
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
          coefIn_0                        :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
          addin                           :   IN    std_logic_vector(52 DOWNTO 0);  -- sfix53_En48
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En24
          tapout                          :   OUT   std_logic_vector(52 DOWNTO 0)  -- sfix53_En48
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterTapSystolicWvldin_24
    USE ENTITY work.FilterTapSystolicWvldin_24(rtl);

  -- Signals
  SIGNAL intdelay_reg                     : std_logic_vector(0 TO 26);  -- ufix1 [27]
  SIGNAL vldShift                         : std_logic;
  SIGNAL vldOutTmp                        : std_logic;
  SIGNAL ZERO_OUT                         : signed(23 DOWNTO 0);  -- sfix24_En24
  SIGNAL addin                            : signed(52 DOWNTO 0);  -- sfix53_En48
  SIGNAL dinDly2                          : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout                           : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly                           : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_1                         : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_1                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_2                         : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_2                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_3                         : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_3                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_4                         : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_4                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_5                         : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_5                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_6                         : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_6                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_7                         : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_7                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_8                         : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_8                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_9                         : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_9                         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_10                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_10                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_11                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_11                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_12                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_12                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_13                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_13                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_14                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_14                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_15                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_15                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_16                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_16                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_17                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_17                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_18                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_18                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_19                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_19                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_20                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_20                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_21                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_21                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_22                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL dinDly_22                        : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL tapout_23                        : std_logic_vector(52 DOWNTO 0);  -- ufix53
  SIGNAL tapout_signed                    : signed(52 DOWNTO 0);  -- sfix53_En48
  SIGNAL dout_cast                        : signed(23 DOWNTO 0);  -- sfix24_En24
  SIGNAL muxOut                           : signed(23 DOWNTO 0);  -- sfix24_En24
  SIGNAL dout_1_re_tmp                    : signed(23 DOWNTO 0);  -- sfix24_En24

BEGIN
  u_FilterTap_1 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix24_En24
              coefIn_0 => coefIn(0),  -- sfix24_En24
              addin => std_logic_vector(addin),  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2,  -- sfix24_En24
              tapout => tapout  -- sfix53_En48
              );

  u_FilterTap_2 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2,  -- sfix24_En24
              coefIn_0 => coefIn(1),  -- sfix24_En24
              addin => tapout,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly,  -- sfix24_En24
              tapout => tapout_1  -- sfix53_En48
              );

  u_FilterTap_3 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly,  -- sfix24_En24
              coefIn_0 => coefIn(2),  -- sfix24_En24
              addin => tapout_1,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_1,  -- sfix24_En24
              tapout => tapout_2  -- sfix53_En48
              );

  u_FilterTap_4 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_1,  -- sfix24_En24
              coefIn_0 => coefIn(3),  -- sfix24_En24
              addin => tapout_2,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_2,  -- sfix24_En24
              tapout => tapout_3  -- sfix53_En48
              );

  u_FilterTap_5 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_2,  -- sfix24_En24
              coefIn_0 => coefIn(4),  -- sfix24_En24
              addin => tapout_3,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_3,  -- sfix24_En24
              tapout => tapout_4  -- sfix53_En48
              );

  u_FilterTap_6 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_3,  -- sfix24_En24
              coefIn_0 => coefIn(5),  -- sfix24_En24
              addin => tapout_4,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_4,  -- sfix24_En24
              tapout => tapout_5  -- sfix53_En48
              );

  u_FilterTap_7 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_4,  -- sfix24_En24
              coefIn_0 => coefIn(6),  -- sfix24_En24
              addin => tapout_5,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_5,  -- sfix24_En24
              tapout => tapout_6  -- sfix53_En48
              );

  u_FilterTap_8 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_5,  -- sfix24_En24
              coefIn_0 => coefIn(7),  -- sfix24_En24
              addin => tapout_6,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_6,  -- sfix24_En24
              tapout => tapout_7  -- sfix53_En48
              );

  u_FilterTap_9 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_6,  -- sfix24_En24
              coefIn_0 => coefIn(8),  -- sfix24_En24
              addin => tapout_7,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_7,  -- sfix24_En24
              tapout => tapout_8  -- sfix53_En48
              );

  u_FilterTap_10 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_7,  -- sfix24_En24
              coefIn_0 => coefIn(9),  -- sfix24_En24
              addin => tapout_8,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_8,  -- sfix24_En24
              tapout => tapout_9  -- sfix53_En48
              );

  u_FilterTap_11 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_8,  -- sfix24_En24
              coefIn_0 => coefIn(10),  -- sfix24_En24
              addin => tapout_9,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_9,  -- sfix24_En24
              tapout => tapout_10  -- sfix53_En48
              );

  u_FilterTap_12 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_9,  -- sfix24_En24
              coefIn_0 => coefIn(11),  -- sfix24_En24
              addin => tapout_10,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_10,  -- sfix24_En24
              tapout => tapout_11  -- sfix53_En48
              );

  u_FilterTap_13 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_10,  -- sfix24_En24
              coefIn_0 => coefIn(12),  -- sfix24_En24
              addin => tapout_11,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_11,  -- sfix24_En24
              tapout => tapout_12  -- sfix53_En48
              );

  u_FilterTap_14 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_11,  -- sfix24_En24
              coefIn_0 => coefIn(13),  -- sfix24_En24
              addin => tapout_12,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_12,  -- sfix24_En24
              tapout => tapout_13  -- sfix53_En48
              );

  u_FilterTap_15 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_12,  -- sfix24_En24
              coefIn_0 => coefIn(14),  -- sfix24_En24
              addin => tapout_13,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_13,  -- sfix24_En24
              tapout => tapout_14  -- sfix53_En48
              );

  u_FilterTap_16 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_13,  -- sfix24_En24
              coefIn_0 => coefIn(15),  -- sfix24_En24
              addin => tapout_14,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_14,  -- sfix24_En24
              tapout => tapout_15  -- sfix53_En48
              );

  u_FilterTap_17 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_14,  -- sfix24_En24
              coefIn_0 => coefIn(16),  -- sfix24_En24
              addin => tapout_15,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_15,  -- sfix24_En24
              tapout => tapout_16  -- sfix53_En48
              );

  u_FilterTap_18 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_15,  -- sfix24_En24
              coefIn_0 => coefIn(17),  -- sfix24_En24
              addin => tapout_16,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_16,  -- sfix24_En24
              tapout => tapout_17  -- sfix53_En48
              );

  u_FilterTap_19 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_16,  -- sfix24_En24
              coefIn_0 => coefIn(18),  -- sfix24_En24
              addin => tapout_17,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_17,  -- sfix24_En24
              tapout => tapout_18  -- sfix53_En48
              );

  u_FilterTap_20 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_17,  -- sfix24_En24
              coefIn_0 => coefIn(19),  -- sfix24_En24
              addin => tapout_18,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_18,  -- sfix24_En24
              tapout => tapout_19  -- sfix53_En48
              );

  u_FilterTap_21 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_18,  -- sfix24_En24
              coefIn_0 => coefIn(20),  -- sfix24_En24
              addin => tapout_19,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_19,  -- sfix24_En24
              tapout => tapout_20  -- sfix53_En48
              );

  u_FilterTap_22 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_19,  -- sfix24_En24
              coefIn_0 => coefIn(21),  -- sfix24_En24
              addin => tapout_20,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_20,  -- sfix24_En24
              tapout => tapout_21  -- sfix53_En48
              );

  u_FilterTap_23 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_20,  -- sfix24_En24
              coefIn_0 => coefIn(22),  -- sfix24_En24
              addin => tapout_21,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_21,  -- sfix24_En24
              tapout => tapout_22  -- sfix53_En48
              );

  u_FilterTap_24 : FilterTapSystolicWvldin_24
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly_21,  -- sfix24_En24
              coefIn_0 => coefIn(23),  -- sfix24_En24
              addin => tapout_22,  -- sfix53_En48
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly_22,  -- sfix24_En24
              tapout => tapout_23  -- sfix53_En48
              );

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          intdelay_reg <= (OTHERS => '0');
        ELSIF dinRegVld = '1' THEN
          intdelay_reg(0) <= dinRegVld;
          intdelay_reg(1 TO 26) <= intdelay_reg(0 TO 25);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;

  vldShift <= intdelay_reg(26);

  vldOutTmp <= dinRegVld AND vldShift;

  ZERO_OUT <= to_signed(16#000000#, 24);

  addin <= to_signed(0, 53);

  tapout_signed <= signed(tapout_23);

  dout_cast <= tapout_signed(47 DOWNTO 24);

  
  muxOut <= ZERO_OUT WHEN vldOutTmp = '0' ELSE
      dout_cast;

  intdelay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dout_1_re_tmp <= to_signed(16#000000#, 24);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dout_1_re_tmp <= to_signed(16#000000#, 24);
        ELSE 
          dout_1_re_tmp <= muxOut;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  dout_1_re <= std_logic_vector(dout_1_re_tmp);

  intdelay_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        doutVld <= '0';
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          doutVld <= '0';
        ELSE 
          doutVld <= vldOutTmp;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


END rtl;

